# -*- coding: utf-8 -*-
"""The 9093 AS Level plan, as data. Read by build_9093.py.

Three kinds of value live here, and each says which it is:

  syllabus   transcribed from the 9093 syllabus (2024-2026, version 2); every objective's text is verified
             against the page it cites before anything is written.
  corpus     counted from the 68 AS question papers and mark schemes (2021-2025) and 9 examiner reports held
             (see operations/analysis/9093-as-english-language-corpus-analysis.md).
  judgement  our design: how the resource is cut into topics, which cards each objective gets.

9093 at AS is examined by task, not by topic: six tasks on two papers, each marked against a level table.
So the topics are two foundations (form, audience, purpose and context; the linguistic toolkit), one on
evidence and analytical writing, and one per paper section. Their objectives are the syllabus's own
statements (pages 12-14 and 19-21). Nothing below reproduces question, text, mark-scheme or report wording.
"""

CODE = '9093'
SLUG = 'as-english-language'
WS_NAME = 'cie-9093-as-2024-2026'

UNITS = {'1': 'Paper 1 Reading', '2': 'Paper 2 Writing'}

# ------------------------------------------------------------------------------------------ topics
# Each objective: key, sub_topic, syllabus_text (verbatim), page, assessment objectives, command words,
# learner_objective (our plain restatement), depth_tier.
TOPICS = [
 {'id': '1.1', 'title': 'Form, audience, purpose and context', 'papers': ['1', '2'],
  'task': 'Both papers: what every reading and writing task rests on',
  'container': ('Knowledge and understanding', 12),
  'sub_topics': {'1.1.1': 'Forms and their conventions', '1.1.2': 'Audience, purpose, genre and context'},
  'objectives': [
   ('A', '1.1.1', 'the conventions of a wide range of written textual forms', 12, ['AO1', 'AO2'], [],
    'Know the conventions of the forms the papers use, and what each convention does for its reader', 2),
   ('B', '1.1.1', 'recognising different nonfiction textual forms and their conventions', 13, ['AO1', 'AO3'], [],
    'Recognise an unseen text’s form from its features, and say what those features are there to do', 3),
   ('C', '1.1.2', 'the significance of audience in both the design and reception of texts', 12, ['AO1', 'AO2'], [],
    'Work out who a text is for, and how that audience shapes what is written and how it is read', 3),
   ('D', '1.1.2', 'the ways in which genre, purpose and context contribute to the meaning of texts', 12, ['AO1', 'AO3'], [],
    'Explain how a text’s genre, purpose and context shape what it means', 3),
   ('E', '1.1.2', 'reading a range of unseen texts', 13, ['AO1'], [],
    'Read an unseen text accurately for its content, viewpoint and situation before analysing it', 2),
  ]},
 {'id': '1.2', 'title': 'Linguistic elements and literary features', 'papers': ['1', '2'],
  'task': 'Both papers: the analytical vocabulary for Paper 1 Questions 1(b) and 2 and Paper 2 Question 1(b)',
  'container': ('the linguistic elements and literary features of texts', 12),
  'sub_topics': {'1.2.1': 'Words: classes, vocabulary, figurative language, sound and form',
                 '1.2.2': 'Grammar: voice, aspect, tense, modality and sentence structure',
                 '1.2.3': 'The whole text: structure, perspective, rhetoric, tone and pragmatics'},
  'objectives': [
   ('A', '1.2.1', 'parts of speech / word classes, vocabulary, figurative language, phonology, morphology', 12, ['AO3'], [],
    'Identify word classes, vocabulary choices, figurative language, sound patterning and word formation, and say what each contributes', 3),
   ('B', '1.2.2', 'voice, aspect, tense, modality', 12, ['AO3'], [],
    'Recognise active and passive voice, aspect, tense and modality, and explain what each choice does', 3),
   ('C', '1.2.2', 'word ordering and sentence structure', 12, ['AO3'], [],
    'Analyse word order, sentence type and sentence length as choices with effects', 3),
   ('D', '1.2.3', 'paragraph- and text-level structure', 12, ['AO3'], [],
    'Analyse how paragraphs, sequence, openings and endings organise a whole text', 3),
   ('E', '1.2.3', 'narrative perspective', 12, ['AO3'], [],
    'Identify narrative perspective and what it lets a writer show or hide', 3),
   ('F', '1.2.3', 'rhetorical devices', 12, ['AO3'], [],
    'Name rhetorical devices precisely and explain how each works on its audience', 3),
   ('G', '1.2.3', 'formality/informality of tone, pragmatics', 12, ['AO3'], [],
    'Describe tone and register, and read what is implied by how something is said', 4),
  ]},
 {'id': '1.3', 'title': 'Evidence and analytical writing', 'papers': ['1', '2'],
  'task': 'Paper 1 Questions 1(b) and 2, and Paper 2 Question 1(b): how an analysis is written',
  'container': ('Skills and techniques', 13),
  'sub_topics': {'1.3.1': 'Selecting evidence', '1.3.2': 'Quotation, comment and argument'},
  'objectives': [
   ('A', '1.3.1', 'selecting and interpreting words and phrases from a text with care and precision', 13, ['AO1', 'AO3'], [],
    'Select the exact words that carry a feature, and interpret them precisely in their context', 3),
   ('B', '1.3.2', 'using quotations and evidence, with judgement, to produce precise, meaningful commentaries', 13, ['AO3'], [],
    'Quote briefly and aptly, so that every word quoted is a word analysed', 3),
   ('C', '1.3.2', 'using appropriate language to link quotations and evidence with explanatory comments', 13, ['AO3'], [],
    'Join evidence to comment with precise analytical language, not stock phrases', 3),
   ('D', '1.3.2', 'integrating quotations and evidence into a cohesive argument', 13, ['AO3'], [],
    'Build analytical paragraphs into one coherent argument about the text', 4),
  ]},
 {'id': '1.4', 'title': 'Directed response and comparison', 'papers': ['1'],
  'task': 'Paper 1 Section A: Question 1(a) directed response (10 marks) and 1(b) comparison (15 marks)',
  'container': ('Section A: Directed response', 19),
  'sub_topics': {'1.4.1': 'Re-using a text for a new purpose', '1.4.2': 'Writing the directed response',
                 '1.4.3': 'What to compare', '1.4.4': 'Writing the comparison'},
  'objectives': [
   ('A', '1.4.1', 'writing in a different style from a text at the same time as re-using the content/material', 13, ['AO1', 'AO2'], [],
    'Re-use a source text’s content in a different form and style, in your own words', 3),
   ('B', '1.4.1', 'writing in the same style as another text', 13, ['AO2'], [],
    'Write in the manner of a given text: its register, voice and characteristic features', 3),
   ('C', '1.4.2', 'writing short, directed pieces in response to a text', 13, ['AO1', 'AO2'], [],
    'Write a short piece directed by a text and a task: the role, audience and purpose it sets', 3),
   ('D', '1.4.2', 'write a directed response of 150–200 words, choosing their vocabulary, style and structure to fit a specific form, purpose and audience', 19, ['AO2'], [],
    'Write 150–200 words whose vocabulary, style and structure fit the form, purpose and audience set', 3),
   ('E', '1.4.3', 'identify, analyse and compare characteristic features of the texts', 19, ['AO1', 'AO3'], ['Compare'],
    'Identify and compare the characteristic features of the source and of your own response', 4),
   ('F', '1.4.3', 'relate these features to the purpose, audience and context of the texts', 19, ['AO1', 'AO3'], ['Compare'],
    'Explain each difference by what each text is for, who it addresses and the situation it comes from', 4),
   ('G', '1.4.4', 'comparing the style and linguistic elements of their own writing with those of a given text', 13, ['AO3'], ['Compare'],
    'Write a comparison that keeps both texts in view in every paragraph', 4),
  ]},
 {'id': '1.5', 'title': 'Text analysis', 'papers': ['1'],
  'task': 'Paper 1 Section B: Question 2 text analysis (25 marks)',
  'container': ('Section B: Text analysis', 20),
  'sub_topics': {'1.5.1': 'Reading the text as a whole', '1.5.2': 'Analysing form, structure and language',
                 '1.5.3': 'Organising the analysis'},
  'objectives': [
   ('A', '1.5.1', 'identify characteristic features of the text, relate them to the meaning, context and audience of the writing, and organise information in their answers', 20, ['AO1', 'AO3'], ['Analyse'],
    'Identify a text’s characteristic features and relate each to its meaning, context and audience', 3),
   ('B', '1.5.1', 'recognising and commenting on the overall style of a text, and exemplifying this through specific instances of language analysis', 13, ['AO1', 'AO3'], [],
    'Characterise a text’s overall style and prove it through specific language choices', 4),
   ('C', '1.5.2', 'comment on aspects of form, structure and language', 20, ['AO3'], ['Analyse'],
    'Analyse form, structure and language, and how they work together', 4),
   ('D', '1.5.2', 'analysing the ways in which linguistic elements come together in a text to create meaning', 13, ['AO3'], [],
    'Show how several linguistic choices combine to create one meaning or effect', 4),
   ('E', '1.5.2', 'writing analytically about the effects produced by a range of linguistic elements and literary features', 13, ['AO3'], [],
    'Write about effects precisely: what a choice leads this reader to think, feel or do', 3),
   ('F', '1.5.3', 'integrating individual analytical points into broader overall responses to texts', 13, ['AO3'], [],
    'Organise an analysis around the text’s purpose and effect, not the order of its paragraphs', 4),
   ('G', '1.5.3', 'write in an appropriate style', 20, ['AO3'], [],
    'Write the analysis in a formal, precise analytical register', 2),
  ]},
 {'id': '2.1', 'title': 'Shorter writing and reflective commentary', 'papers': ['2'],
  'task': 'Paper 2 Section A: Question 1(a) shorter writing (15 marks) and 1(b) reflective commentary (10 marks)',
  'container': ('Section A: Shorter writing and reflective commentary', 20),
  'sub_topics': {'2.1.1': 'Reading the brief', '2.1.2': 'Writing within 400 words',
                 '2.1.3': 'What a reflective commentary does', '2.1.4': 'Writing the commentary'},
  'objectives': [
   ('A', '2.1.1', 'writing for a specified audience and purpose, to fulfil the brief provided', 14, ['AO2'], [],
    'Decode a brief (form, audience, purpose, role and the focus the prompt adds) and fulfil all of it', 3),
   ('B', '2.1.2', 'write a response of no more than 400 words to a prompt, choosing their vocabulary, style and structure to fit a specific form, purpose and audience', 20, ['AO2'], [],
    'Write up to 400 words that use the space well, in the vocabulary, style and structure the brief needs', 3),
   ('C', '2.1.2', 'capable of adapting the style of their writing to fit a diverse range of forms, audiences, purposes and contexts', 13, ['AO2'], [],
    'Adapt your style across forms and audiences: the same content sounds different in a speech, an email and a leaflet', 3),
   ('D', '2.1.3', 'reflecting upon and evaluating the qualities of their own writing, including aspects relating to its purpose, form and audience', 14, ['AO3'], [],
    'Reflect on your own writing and judge it against the brief: its purpose, form and audience', 4),
   ('E', '2.1.3', 'write a reflective commentary explaining how their linguistics choices have contributed to fulfilling the brief in part (a)', 20, ['AO3'], [],
    'Explain how your own linguistic choices fulfil the brief, with evidence quoted from your text', 4),
   ('F', '2.1.4', 'focus on their choices of form, structure and language, and to analyse how these stylistic choices relate to audience and shape meaning', 20, ['AO3'], [],
    'Cover form, structure and language in the commentary, each tied to the audience and to meaning', 4),
  ]},
 {'id': '2.2', 'title': 'Structuring longer writing', 'papers': ['2'],
  'task': 'Paper 2 Section B: structure and development in all three categories (25 marks)',
  'container': ('Section B: Extended writing', 21),
  'sub_topics': {'2.2.1': 'Whole-text structure', '2.2.2': 'Paragraphs and development'},
  'objectives': [
   ('A', '2.2.1', 'producing an appropriate structure for longer pieces of writing', 14, ['AO2'], [],
    'Choose a whole-text structure that fits the category and the task', 3),
   ('B', '2.2.1', 'organising writing to achieve specific effects', 14, ['AO2'], [],
    'Order material for effect: what to hold back, what to set side by side, what to end on', 4),
   ('C', '2.2.1', 'produce a continuous piece of writing of 600–900 words', 21, ['AO2'], [],
    'Plan and write one continuous piece of 600–900 words, with the words shared across its sections', 3),
   ('D', '2.2.2', 'structuring paragraphs', 14, ['AO2'], [],
    'Build paragraphs with topic sentences, connectives, internal coherence and discourse markers', 2),
   ('E', '2.2.2', 'develop their writing in a manner appropriate to the form, purpose and audience', 21, ['AO2'], [],
    'Develop each point or moment as fully as the form, purpose and audience need', 3),
  ]},
 {'id': '2.3', 'title': 'Imaginative and descriptive writing', 'papers': ['2'],
  'task': 'Paper 2 Section B: the imaginative/descriptive question (25 marks)',
  'container': ('imaginative/descriptive', 21),
  'sub_topics': {'2.3.1': 'Narrative writing', '2.3.2': 'Descriptive writing'},
  'objectives': [
   ('A', '2.3.1', 'Freytag’s Pyramid in imaginative writing', 14, ['AO2'], [],
    'Shape a story through exposition, rising action, climax, falling action and resolution', 3),
   ('B', '2.3.1', 'withholding key information in imaginative writing', 14, ['AO2'], [],
    'Build suspense by withholding and then releasing key information', 4),
   ('C', '2.3.2', 'imagery in descriptive writing', 14, ['AO2'], [],
    'Create a scene through precise, original imagery and sensory detail', 3),
   ('D', '2.3.2', 'narrative writing, and descriptive writing', 21, ['AO2'], [],
    'Tell a narrative task from a descriptive one, and write what each needs', 2),
  ]},
 {'id': '2.4', 'title': 'Discursive and argumentative writing', 'papers': ['2'],
  'task': 'Paper 2 Section B: the discursive/argumentative question (25 marks)',
  'container': ('discursive/argumentative', 21),
  'sub_topics': {'2.4.1': 'Building the case', '2.4.2': 'The language of argument'},
  'objectives': [
   ('A', '2.4.1', 'dialectical structure in discursive writing', 14, ['AO2'], [],
    'Structure a discursive piece dialectically: a view, the opposing view, a reasoned resolution', 3),
   ('B', '2.4.1', 'juxtaposing counterarguments in discursive writing', 14, ['AO2'], [],
    'Set counterarguments beside your points and answer them', 4),
   ('C', '2.4.2', 'rhetorical devices in argumentative writing', 14, ['AO2'], [],
    'Use rhetorical devices with control to persuade a named audience', 3),
  ]},
 {'id': '2.5', 'title': 'Review and critical writing', 'papers': ['2'],
  'task': 'Paper 2 Section B: the review/critical question (25 marks)',
  'container': ('review/critical', 21),
  'sub_topics': {'2.5.1': 'The shape of a review', '2.5.2': 'Evaluative language'},
  'objectives': [
   ('A', '2.5.1', 'introductory, summary and evaluative sections in review writing', 14, ['AO2'], [],
    'Structure a review: an introduction, an account of what is reviewed, and evaluation leading to a verdict', 3),
   ('B', '2.5.1', 'evidentiary logic in critical writing', 14, ['AO2'], [],
    'Support every judgement with specific evidence from the thing reviewed', 4),
   ('C', '2.5.2', 'evaluative lexis in critical writing', 14, ['AO2'], [],
    'Use precise, graded evaluative vocabulary', 3),
  ]},
 {'id': '2.6', 'title': 'Expression, range and accuracy', 'papers': ['1', '2'],
  'task': 'Both papers: the writing marks (AO2) in Paper 1 Question 1(a) and in Paper 2 Questions 1(a) and Section B',
  'container': ('Write effectively, creatively, accurately and appropriately, for a range of audiences and purposes.', 11),
  'sub_topics': {'2.6.1': 'Range of language', '2.6.2': 'Accuracy at sentence and word level'},
  'objectives': [
   ('A', '2.6.1', 'using a range of appropriate linguistic elements and literary features', 14, ['AO2'], [],
    'Use a range of vocabulary, sentence structures and literary features chosen for the task', 3),
   ('B', '2.6.1', 'express their ideas clearly, coherently and accurately, using an appropriate range of language', 21, ['AO2'], [],
    'Write clearly and coherently, with a range of language you can control', 3),
   ('C', '2.6.2', 'expressing ideas accurately and clearly at both sentence and word level', 14, ['AO2'], [],
    'Write accurately: sentence boundaries, agreement, tense, punctuation and spelling', 2),
  ]},
]

# --------------------------------------------------------------------------------- flashcard slots
# (objective key, subtype, what the card teaches, command word or None, tariff or None, misconception id or None)
# 9093 has no point-marked short items: every question is marked by levels. So no flashcard models a paper
# item's command word or tariff, and every card carries None for both. The command words (Compare,
# Analyse) sit on the performance tasks that model Paper 1 Questions 1(b) and 2.
_ = None
F = {}
F['1.1'] = [
 ('A', 'DEF', 'form: the kind of text (article, speech, email, review) and the conventions its readers expect', _, _, _),
 ('A', 'DEF', 'conventions: the features a form’s readers expect, and which a writer can follow or break', _, _, _),
 ('A', 'FEATURE', 'the conventions of a newspaper or magazine article: headline, standfirst, byline, quoted voices, short paragraphs', _, _, _),
 ('A', 'FEATURE', 'the conventions of a speech: address to the audience, signposting, repetition for listeners, a memorable close', _, _, _),
 ('A', 'FEATURE', 'the conventions of a formal letter and of an email: salutation, purpose stated early, register fitted to the reader, sign-off', _, _, _),
 ('A', 'FEATURE', 'the conventions of a blog: personal voice, direct address, informal register, headings, an invitation to respond', _, _, _),
 ('A', 'FEATURE', 'the conventions of a review: what is reviewed, the criteria, the evidence, the verdict', _, _, _),
 ('A', 'FEATURE', 'the conventions of a diary and of a memoir: first person, dated or looking back, reflection beside events', _, _, _),
 ('A', 'FEATURE', 'the conventions of a leaflet, brochure or advertisement: headings, direct address, imperatives, benefits, a call to action', _, _, _),
 ('A', 'FEATURE', 'the conventions of a report: title, stated purpose, findings in sections, recommendations, an impersonal register', _, _, _),
 ('A', 'FEATURE', 'the conventions of a podcast or scripted talk: a host’s voice, spoken markers, signposting for listeners', _, _, _),
 ('A', 'WHY', 'why a convention is there: each one does a job for the reader, and an analysis names the job', _, _, _),
 ('A', 'MISCON', 'listing a form’s conventions as if the list were the analysis', _, _, 'MC-9093-1.1-01'),
 ('B', 'PROC', 'identifying an unseen text’s form: layout, address, voice, register, and what it is for', _, _, _),
 ('B', 'DIST', 'fiction versus non-fiction that uses narrative techniques (memoir, travel writing)', _, _, _),
 ('B', 'INTERP', 'identify the form of a supplied original 80-word extract from its features, naming the features', _, _, _),
 ('B', 'INTERP', 'identify the two forms blended in a supplied original extract, and which features come from each', _, _, _),
 ('C', 'DEF', 'audience: the readers or listeners a text is designed for, stated or implied', _, _, _),
 ('C', 'DEF', 'implied reader: the reader a text’s choices assume, who may not be who actually reads it', _, _, _),
 ('C', 'DIST', 'the audience a text is designed for versus the audience that receives it', _, _, _),
 ('C', 'PROC', 'working out an audience: who is addressed, what they are assumed to know, what they are asked to do', _, _, _),
 ('C', 'INTERP', 'what a supplied original sentence assumes about its reader’s age, knowledge and values', _, _, _),
 ('C', 'MISCON', 'writing in the wrong role, or for the wrong purpose, when the task sets both', _, _, 'MC-9093-1.1-02'),
 ('D', 'DEF', 'purpose: what a text sets out to do (inform, persuade, entertain, advise, argue), often more than one thing', _, _, _),
 ('D', 'DEF', 'genre: a family of texts that share a purpose and conventions', _, _, _),
 ('D', 'DEF', 'context: the situation a text is produced and read in: when, where, by whom, for whom, through what medium', _, _, _),
 ('D', 'DIST', 'a primary purpose versus a secondary one, and how to tell which dominates', _, _, _),
 ('D', 'DIST', 'the context of production versus the context of reception', _, _, _),
 ('D', 'WHY', 'why the same fact reads differently in a news report, a blog and an advertisement', _, _, _),
 ('D', 'INTERP', 'how the medium and date implied by a supplied original extract change what its words mean', _, _, _),
 ('D', 'MISCON', 'naming the purpose and audience in the first sentence and never linking a feature to them again', _, _, 'MC-9093-1.1-03'),
 ('E', 'PROC', 'a first reading of an unseen text: form, audience, purpose, viewpoint and overall effect, before any feature', _, _, _),
 ('E', 'DIST', 'what a text says versus what it does', _, _, _),
 ('E', 'WHY', 'why gist and viewpoint come before features: a feature can only be analysed as a means to an effect', _, _, _),
 ('E', 'MISCON', 'misreading a detail of the source and building the answer on the error', _, _, 'MC-9093-1.1-04'),
]
F['1.2'] = [
 ('A', 'DEF', 'word classes: noun, verb, adjective, adverb, and what each does in a sentence', _, _, _),
 ('A', 'DEF', 'pronoun and determiner', _, _, _),
 ('A', 'DEF', 'lexis: the vocabulary of a text, and lexical choice', _, _, _),
 ('A', 'DEF', 'semantic field (lexical field): a group of words from one area of meaning', _, _, _),
 ('A', 'DEF', 'denotation and connotation', _, _, _),
 ('A', 'DEF', 'modifier: a word or phrase that adds detail to a noun or verb (premodifier, postmodifier)', _, _, _),
 ('A', 'DEF', 'metaphor, simile and personification', _, _, _),
 ('A', 'DEF', 'pathetic fallacy', _, _, _),
 ('A', 'DEF', 'phonology in written texts: alliteration, assonance, sibilance, plosives, onomatopoeia', _, _, _),
 ('A', 'DEF', 'morphology: how words are built (prefix, suffix, compound, coinage)', _, _, _),
 ('A', 'DIST', 'concrete versus abstract nouns, and what a shift between them does', _, _, _),
 ('A', 'MECH', 'how a semantic field in a supplied original extract builds a view of its subject', _, _, _),
 ('A', 'MECH', 'how a supplied original metaphor shapes the reader’s attitude to what it describes', _, _, _),
 ('A', 'MECH', 'how sound patterning in a supplied original sentence reinforces its meaning', _, _, _),
 ('A', 'MECH', 'how a coined compound in a supplied original sentence signals informality or novelty', _, _, _),
 ('A', 'MISCON', 'calling words “positive” or “negative” in connotation and stopping there', _, _, 'MC-9093-1.2-01'),
 ('A', 'MISCON', 'naming the wrong feature: a simile called a metaphor, an adjective called an adverb', _, _, 'MC-9093-1.2-06'),
 ('B', 'DEF', 'active and passive voice', _, _, _),
 ('B', 'DEF', 'aspect: progressive and perfect', _, _, _),
 ('B', 'DEF', 'tense, and the present tense used for past events', _, _, _),
 ('B', 'DEF', 'modality: modal verbs and adverbs expressing certainty, possibility and obligation', _, _, _),
 ('B', 'DIST', 'grammatical voice (active, passive) versus a writer’s voice (their persona)', _, _, _),
 ('B', 'MECH', 'how the passive in a supplied original sentence hides or removes the agent', _, _, _),
 ('B', 'MECH', 'how high and low modality in two supplied original sentences changes a writer’s authority', _, _, _),
 ('B', 'MECH', 'how a shift from past to present tense in a supplied original extract creates immediacy', _, _, _),
 ('B', 'APP', 'rewrite a supplied original active sentence in the passive, and say what the change does', _, _, _),
 ('C', 'DEF', 'simple, compound and complex sentences', _, _, _),
 ('C', 'DEF', 'minor sentence', _, _, _),
 ('C', 'DEF', 'syntax and word order', _, _, _),
 ('C', 'DEF', 'fronting: moving an element to the start of a sentence for focus', _, _, _),
 ('C', 'MECH', 'how a short sentence after longer ones in a supplied original extract creates emphasis', _, _, _),
 ('C', 'MECH', 'how a list of three in a supplied original sentence builds weight', _, _, _),
 ('C', 'MECH', 'how fronting in a supplied original sentence shifts the reader’s focus', _, _, _),
 ('C', 'DIST', 'labelling a sentence type versus analysing what it does', _, _, _),
 ('C', 'MISCON', 'labelling sentences simple, compound or complex and saying nothing about their effect', _, _, 'MC-9093-1.2-03'),
 ('D', 'DEF', 'structure: how a whole text is organised and sequenced', _, _, _),
 ('D', 'DEF', 'cohesion: how sentences and paragraphs are tied together', _, _, _),
 ('D', 'DEF', 'discourse marker', _, _, _),
 ('D', 'DEF', 'anaphoric and cataphoric reference', _, _, _),
 ('D', 'FEATURE', 'the structural features worth tracking: the opening, shifts of focus, paragraph length, sequence, repetition across the text, the ending', _, _, _),
 ('D', 'MECH', 'how a one-sentence paragraph in a supplied original extract marks a turning point', _, _, _),
 ('D', 'MECH', 'how an ending that returns to the opening (a cyclical structure) shapes the reader’s final view', _, _, _),
 ('D', 'DIST', 'structure versus language: what each covers in an analysis', _, _, _),
 ('D', 'MISCON', 'leaving structure out, or describing where things are without saying what the arrangement does', _, _, 'MC-9093-1.2-07'),
 ('E', 'DEF', 'first-person narration', _, _, _),
 ('E', 'DEF', 'second-person address', _, _, _),
 ('E', 'DEF', 'third-person narration, limited and omniscient', _, _, _),
 ('E', 'DIST', 'the narrator versus the author', _, _, _),
 ('E', 'MECH', 'how first-person narration in a supplied original extract limits what the reader knows', _, _, _),
 ('E', 'MISCON', 'using a narrative term loosely: any first-person text called stream of consciousness', _, _, 'MC-9093-1.2-04'),
 ('F', 'DEF', 'rhetorical question', _, _, _),
 ('F', 'DEF', 'direct address', _, _, _),
 ('F', 'DEF', 'tricolon (a list of three)', _, _, _),
 ('F', 'DEF', 'anaphora', _, _, _),
 ('F', 'DEF', 'antithesis', _, _, _),
 ('F', 'DEF', 'hyperbole', _, _, _),
 ('F', 'MECH', 'how a supplied original rhetorical question positions its audience', _, _, _),
 ('F', 'DIST', 'a rhetorical question versus a question that expects an answer', _, _, _),
 ('F', 'MISCON', 'calling every question “rhetorical”, and treating rhetorical questions as the only rhetorical device', _, _, 'MC-9093-1.2-05'),
 ('G', 'DEF', 'tone', _, _, _),
 ('G', 'DEF', 'register', _, _, _),
 ('G', 'DEF', 'formality and informality, and the features that mark each', _, _, _),
 ('G', 'DEF', 'pragmatics: meaning that comes from context and implication rather than the words alone', _, _, _),
 ('G', 'DEF', 'implicature: what a speaker or writer implies without stating it', _, _, _),
 ('G', 'DIST', 'tone versus register', _, _, _),
 ('G', 'DIST', 'how common a word is versus how formal it is', _, _, _),
 ('G', 'INTERP', 'what a supplied original polite request implies beyond its words', _, _, _),
 ('G', 'MECH', 'how a shift of register in a supplied original extract signals a change in the writer’s relationship with the reader', _, _, _),
 ('G', 'MISCON', 'treating a word’s frequency, its formality and the text’s tone as the same thing', _, _, 'MC-9093-1.2-02'),
]
F['1.3'] = [
 ('A', 'DEF', 'evidence: the exact words in a text that show a feature', _, _, _),
 ('A', 'PROC', 'selecting evidence: the shortest stretch of words that carries the feature', _, _, _),
 ('A', 'APP', 'select the three words in a supplied original 60-word extract that best show its writer’s attitude', _, _, _),
 ('A', 'DIST', 'a quotation versus a paraphrase as evidence', _, _, _),
 ('A', 'INTERP', 'interpret one word from a supplied original sentence: what it means there and what it suggests', _, _, _),
 ('A', 'MISCON', 'making analytical points with no words from the text to support them', _, _, 'MC-9093-1.3-02'),
 ('B', 'DEF', 'embedded quotation', _, _, _),
 ('B', 'PROC', 'embedding a quotation so that it fits the grammar of your own sentence', _, _, _),
 ('B', 'APP', 'embed a supplied original phrase in an analytical sentence of your own', _, _, _),
 ('B', 'WHY', 'why short quotations work: every word quoted can then be analysed', _, _, _),
 ('B', 'DIST', 'a line reference versus a quotation', _, _, _),
 ('B', 'MISCON', 'quoting whole sentences, or citing a range of lines, instead of the words that matter', _, _, 'MC-9093-1.3-01'),
 ('C', 'FEATURE', 'analytical verbs that link evidence to effect: suggests, conveys, evokes, positions, undercuts', _, _, _),
 ('C', 'DIST', 'a precise statement of effect versus a stock one', _, _, _),
 ('C', 'APP', 'rewrite a supplied stock comment on effect as a precise one', _, _, _),
 ('C', 'APP', 'rewrite a second supplied stock comment so that it names the audience affected', _, _, _),
 ('C', 'MISCON', 'stock effect phrases that could follow any quotation', _, _, 'MC-9093-1.3-03'),
 ('D', 'DEF', 'an analytical paragraph: a claim, its evidence, the analysis, the link to purpose', _, _, _),
 ('D', 'PROC', 'building an analytical paragraph in four moves', _, _, _),
 ('D', 'FEATURE', 'what a coherent line of argument across a whole analysis contains', _, _, _),
 ('D', 'DIST', 'an argument about a text versus a list of observations on it', _, _, _),
 ('D', 'EVAL', 'judge which of two supplied original analytical paragraphs makes the stronger point, and why', _, _, _),
 ('D', 'MISCON', 'a string of separate observations with no argument joining them', _, _, 'MC-9093-1.3-04'),
]
F['1.4'] = [
 ('A', 'DEF', 'directed response: a new text written from a source for a set form, audience and purpose', _, _, _),
 ('A', 'PROC', 'reshaping a source: select the content the new purpose needs, then change its register, voice and structure', _, _, _),
 ('A', 'DIST', 're-using a source’s content versus lifting its wording', _, _, _),
 ('A', 'APP', 'rewrite a supplied original 50-word extract as the opening of an email to a friend, keeping its content', _, _, _),
 ('A', 'APP', 'rewrite a supplied original 50-word extract as a formal public notice, keeping its content', _, _, _),
 ('A', 'MISCON', 'lifting phrases and sentences from the source into the response', _, _, 'MC-9093-1.4-01'),
 ('A', 'MISCON', 'summarising the source instead of reshaping it for the new form and audience', _, _, 'MC-9093-1.4-02'),
 ('A', 'MISCON', 'adding material the source does not support, until the response tells a different story', _, _, 'MC-9093-1.4-04'),
 ('B', 'DEF', 'writing in the style of a text: taking on its register, sentence patterns, voice and signature features', _, _, _),
 ('B', 'PROC', 'matching a style: name its register, its typical sentence, its voice, two signature features, then write', _, _, _),
 ('B', 'APP', 'continue a supplied original 60-word extract for two sentences in the same style', _, _, _),
 ('C', 'PROC', 'decoding a directed-response task: role, form, audience, purpose, and what must come from the source', _, _, _),
 ('C', 'WHY', 'why the role matters: it decides the voice and the point of view', _, _, _),
 ('C', 'DIST', 'writing as the role versus writing about the role', _, _, _),
 ('D', 'FEATURE', 'what a 150–200-word directed response contains: the form’s key conventions, the source’s relevant content, a fitted register', _, _, _),
 ('D', 'PROC', 'sharing 150–200 words across an opening, a body and a close', _, _, _),
 ('D', 'EVAL', 'judge which of two supplied original openings better fits a named form and audience', _, _, _),
 ('D', 'MISCON', 'writing far more, or far less, than 150–200 words', _, _, 'MC-9093-1.4-03'),
 ('D', 'MISCON', 'leaving out the conventions the form needs (a speech with no address to its audience)', _, _, 'MC-9093-1.4-05'),
 ('E', 'DEF', 'comparison: similarities and differences, each explained', _, _, _),
 ('E', 'PROC', 'planning a comparison: the purpose, audience and form of each text first, then features matched in pairs', _, _, _),
 ('E', 'FEATURE', 'comparative connectives: whereas, similarly, in contrast, both, unlike', _, _, _),
 ('E', 'APP', 'write one comparative sentence on a supplied pair of original openings', _, _, _),
 ('E', 'MISCON', 'writing mostly about the source and little about your own response', _, _, 'MC-9093-1.4-06'),
 ('E', 'MISCON', 'comparing what the two texts say instead of how they are written', _, _, 'MC-9093-1.4-07'),
 ('F', 'WHY', 'why each difference has a reason: a different purpose, audience or context', _, _, _),
 ('F', 'MECH', 'how a change of audience between a supplied pair of original sentences changes their register', _, _, _),
 ('F', 'INTERP', 'what a supplied pair of original sentences shows about the two texts’ purposes', _, _, _),
 ('F', 'MISCON', 'naming a tone without pointing to the language that creates it', _, _, 'MC-9093-1.4-09'),
 ('G', 'FEATURE', 'what a strong comparative paragraph contains', _, _, _),
 ('G', 'DIST', 'comparing throughout versus two separate commentaries placed side by side', _, _, _),
 ('G', 'MISCON', 'discussing each text in turn without ever referring across to the other', _, _, 'MC-9093-1.4-08'),
]
F['1.5'] = [
 ('A', 'DEF', 'characteristic features: the features that make a text the kind of text it is', _, _, _),
 ('A', 'PROC', 'the opening move of an analysis: form, audience, purpose and context, and the overall effect in one sentence', _, _, _),
 ('A', 'INTERP', 'what a supplied original 80-word opening signals about its text’s audience and purpose', _, _, _),
 ('A', 'MISCON', 'responding to the topic of the text (agreeing, arguing, explaining the subject) instead of analysing the writing', _, _, 'MC-9093-1.5-05'),
 ('B', 'DEF', 'style: the overall manner of a text, produced by its choices together', _, _, _),
 ('B', 'PROC', 'characterising a style: two or three precise adjectives, then the choices that produce them', _, _, _),
 ('B', 'APP', 'characterise the style of a supplied original extract in one sentence, then prove it with two choices', _, _, _),
 ('B', 'DIST', 'style versus tone', _, _, _),
 ('B', 'MISCON', 'describing the overall style in general terms that are never proved by a single example', _, _, 'MC-9093-1.5-04'),
 ('C', 'PROC', 'form, structure and language: what each heading covers in an analysis', _, _, _),
 ('C', 'DIST', 'form versus structure', _, _, _),
 ('C', 'FEATURE', 'the structural features worth analysing in a non-fiction text', _, _, _),
 ('C', 'MISCON', 'summarising or retelling the text instead of analysing it', _, _, 'MC-9093-1.5-01'),
 ('D', 'MECH', 'how two supplied original language choices combine to create one effect', _, _, _),
 ('D', 'MECH', 'how a structural choice and a language choice in a supplied original extract support each other', _, _, _),
 ('D', 'WHY', 'why features are analysed as a system: their effect is joint, not one by one', _, _, _),
 ('E', 'DEF', 'effect: what a choice leads the reader to think, feel or do', _, _, _),
 ('E', 'PROC', 'the analytical sequence: feature, evidence, effect on this reader, link to purpose', _, _, _),
 ('E', 'MECH', 'how a supplied original semantic field shapes the reader’s view of the subject', _, _, _),
 ('E', 'MECH', 'how a contrast between two supplied original paragraphs creates a turning point', _, _, _),
 ('E', 'MISCON', 'feature-spotting: naming devices and sentence types without saying what they do', _, _, 'MC-9093-1.5-03'),
 ('F', 'PROC', 'organising an analysis by effect or purpose, not by the order of the paragraphs', _, _, _),
 ('F', 'DIST', 'a whole-text analysis versus a walk through the text', _, _, _),
 ('F', 'FEATURE', 'what the introduction of a text analysis should do', _, _, _),
 ('F', 'FEATURE', 'what the conclusion of a text analysis should do', _, _, _),
 ('F', 'MISCON', 'working through the text paragraph by paragraph, or jumping around it without a line of argument', _, _, 'MC-9093-1.5-02'),
 ('G', 'FEATURE', 'the analytical register: third person, present tense, precise terms, no chat', _, _, _),
 ('G', 'DIST', 'analytical commentary versus conversational commentary', _, _, _),
]
F['2.1'] = [
 ('A', 'DEF', 'brief: the specification a piece of writing must fulfil', _, _, _),
 ('A', 'PROC', 'decoding a brief: form, audience, purpose, role and the focus sentence', _, _, _),
 ('A', 'DIST', 'a task’s form versus its purpose: a speech that informs versus a speech that persuades', _, _, _),
 ('A', 'EVAL', 'judge which of two supplied original openings better fulfils a stated brief, and why', _, _, _),
 ('A', 'MISCON', 'writing in a different form from the one set: a story where a description or speech was asked for', _, _, 'MC-9093-2.1-02'),
 ('A', 'MISCON', 'ignoring the role or the occasion the brief sets', _, _, 'MC-9093-2.1-03'),
 ('A', 'MISCON', 'missing the focus the prompt adds (to persuade, to create a sense of something)', _, _, 'MC-9093-2.1-04'),
 ('B', 'PROC', 'planning up to 400 words: an opening, two or three developed sections, a close', _, _, _),
 ('B', 'WHY', 'why a very short answer loses marks: development is part of achieving the task', _, _, _),
 ('B', 'FEATURE', 'what the opening of a 400-word piece must do', _, _, _),
 ('B', 'MISCON', 'writing far less than the space allows, so nothing is developed', _, _, 'MC-9093-2.1-01'),
 ('C', 'APP', 'rewrite a supplied original sentence for a speech, then for an email, then for a leaflet', _, _, _),
 ('C', 'MECH', 'how the same content changes when the audience changes from classmates to officials', _, _, _),
 ('C', 'DIST', 'formal versus informal register, and what decides which fits', _, _, _),
 ('D', 'DEF', 'reflective commentary: an analysis of your own choices against the brief', _, _, _),
 ('D', 'WHY', 'why a commentary is analysis, not a summary of what you wrote', _, _, _),
 ('D', 'DIST', 'what your text says versus what your choices do', _, _, _),
 ('D', 'MISCON', 'retelling the content of your own piece instead of analysing its choices', _, _, 'MC-9093-2.1-06'),
 ('E', 'PROC', 'a commentary paragraph: the choice, a quotation from your text, its effect, the link to the brief', _, _, _),
 ('E', 'APP', 'write one commentary sentence on a supplied original line from a speech', _, _, _),
 ('E', 'MISCON', 'a commentary with no quotation from the text it is about', _, _, 'MC-9093-2.1-05'),
 ('E', 'MISCON', 'listing the features you used (“I used adjectives and metaphors”) and stopping there', _, _, 'MC-9093-2.1-08'),
 ('F', 'FEATURE', 'what a commentary must cover: form, structure and language, each tied to the audience', _, _, _),
 ('F', 'PROC', 'sharing a commentary across form, structure and language', _, _, _),
 ('F', 'MISCON', 'a commentary on structure alone, or on language alone', _, _, 'MC-9093-2.1-07'),
]
F['2.2'] = [
 ('A', 'DEF', 'whole-text structure: the shape of a piece from its opening to its ending', _, _, _),
 ('A', 'FEATURE', 'the shape each category tends to take: a story’s arc, a discursive piece’s dialectic, a review’s sections', _, _, _),
 ('A', 'PROC', 'planning a 600–900-word piece: purpose, shape, sections, words per section', _, _, _),
 ('A', 'DIST', 'chronological versus thematic organisation', _, _, _),
 ('B', 'MECH', 'how holding back an outcome until the end keeps a reader reading', _, _, _),
 ('B', 'MECH', 'how placing a counterargument beside a point strengthens an argument', _, _, _),
 ('B', 'MECH', 'how ending on one image or line makes a piece memorable', _, _, _),
 ('B', 'DIST', 'an ending versus a stop', _, _, _),
 ('B', 'MISCON', 'an ending that stops abruptly or rushes, with no resolution or final point', _, _, 'MC-9093-2.2-02'),
 ('C', 'PROC', 'sharing 600–900 words across the sections of a plan', _, _, _),
 ('C', 'WHY', 'why the lower limit matters: development needs room', _, _, _),
 ('C', 'MISCON', 'writing well short of 600 words, often because Section A took too long', _, _, 'MC-9093-2.2-03'),
 ('D', 'DEF', 'topic sentence', _, _, _),
 ('D', 'DEF', 'connectives and discourse markers', _, _, _),
 ('D', 'DEF', 'internal coherence: every sentence in a paragraph serving its topic', _, _, _),
 ('D', 'APP', 'write a topic sentence for a supplied original paragraph that lacks one', _, _, _),
 ('D', 'APP', 'join three supplied original sentences into one coherent paragraph with discourse markers', _, _, _),
 ('D', 'MISCON', 'writing without paragraphs, or paragraphing at random', _, _, 'MC-9093-2.2-01'),
 ('E', 'DEF', 'development: the detail, example or explanation that carries a point or a moment further', _, _, _),
 ('E', 'PROC', 'developing a point: claim, reason, example, consequence', _, _, _),
 ('E', 'APP', 'develop a supplied bare original sentence into three sentences', _, _, _),
 ('E', 'DIST', 'developing a point versus repeating it', _, _, _),
]
F['2.3'] = [
 ('A', 'DEF', 'Freytag’s Pyramid: exposition, rising action, climax, falling action, resolution', _, _, _),
 ('A', 'DEF', 'exposition', _, _, _),
 ('A', 'DEF', 'climax', _, _, _),
 ('A', 'DEF', 'resolution', _, _, _),
 ('A', 'PROC', 'planning a 600–900-word story on the pyramid: one conflict, few characters, one setting', _, _, _),
 ('A', 'DIST', 'a contained plot versus a chain of events', _, _, _),
 ('A', 'MISCON', 'a plot overloaded with events and characters, or an unbelievable one', _, _, 'MC-9093-2.3-02'),
 ('A', 'MISCON', 'dialogue that runs on, carries no story and is badly punctuated', _, _, 'MC-9093-2.3-06'),
 ('B', 'DEF', 'suspense', _, _, _),
 ('B', 'MECH', 'how withholding a detail creates suspense', _, _, _),
 ('B', 'MECH', 'how slowing the pace at the climax builds tension', _, _, _),
 ('B', 'APP', 'rewrite a supplied original paragraph so that it withholds its key fact until the last sentence', _, _, _),
 ('B', 'MISCON', 'not creating the effect the question asks for (drama, suspense, mystery)', _, _, 'MC-9093-2.3-04'),
 ('C', 'DEF', 'imagery', _, _, _),
 ('C', 'DEF', 'sensory detail', _, _, _),
 ('C', 'DEF', 'atmosphere', _, _, _),
 ('C', 'MECH', 'how one precise image in a supplied original sentence sets a mood', _, _, _),
 ('C', 'APP', 'rewrite a supplied flat original sentence with precise sensory detail', _, _, _),
 ('C', 'DIST', 'precise detail versus a pile of adjectives', _, _, _),
 ('C', 'MISCON', 'stacking adjectives in place of one precise detail', _, _, 'MC-9093-2.3-03'),
 ('D', 'DIST', 'describing versus narrating', _, _, _),
 ('D', 'FEATURE', 'what a descriptive piece needs: a fixed place or moment, a moving focus, detail, no plot', _, _, _),
 ('D', 'FEATURE', 'what a narrative piece needs: a character, a conflict, a change', _, _, _),
 ('D', 'PROC', 'using a given opening or closing sentence: build out from it, or build towards it', _, _, _),
 ('D', 'MISCON', 'a description that turns into a story of events', _, _, 'MC-9093-2.3-01'),
 ('D', 'MISCON', 'leaving out, or changing, the sentence the question says the story must begin or end with', _, _, 'MC-9093-2.3-05'),
]
F['2.4'] = [
 ('A', 'DEF', 'discursive writing: exploring an issue from more than one side', _, _, _),
 ('A', 'DEF', 'argumentative writing: arguing for one position', _, _, _),
 ('A', 'DIST', 'discursive versus argumentative writing, and what the task’s wording signals', _, _, _),
 ('A', 'DEF', 'dialectical structure: a thesis, its antithesis, and a synthesis', _, _, _),
 ('A', 'PROC', 'planning a dialectical piece', _, _, _),
 ('A', 'FEATURE', 'the conventions of an opinion article, an essay, a speech and a letter to an editor', _, _, _),
 ('A', 'MISCON', 'a one-sided list of reasons with a one-line conclusion', _, _, 'MC-9093-2.4-01'),
 ('A', 'MISCON', 'narrowing a broad issue to one aspect of it', _, _, 'MC-9093-2.4-03'),
 ('A', 'MISCON', 'writing in the wrong form: an article with headline and subheadings when an essay was set', _, _, 'MC-9093-2.4-05'),
 ('B', 'DEF', 'counterargument', _, _, _),
 ('B', 'DEF', 'rebuttal', _, _, _),
 ('B', 'DEF', 'concession', _, _, _),
 ('B', 'MECH', 'how a concession followed by a rebuttal makes an argument more convincing', _, _, _),
 ('B', 'APP', 'write a rebuttal to a supplied original counterargument', _, _, _),
 ('B', 'EVAL', 'judge how convincing a supplied original argument paragraph is, and what it overlooks', _, _, _),
 ('B', 'MISCON', 'repeating the same point in new words instead of developing it', _, _, 'MC-9093-2.4-02'),
 ('C', 'MECH', 'how tricolon and anaphora in a supplied original sentence add force', _, _, _),
 ('C', 'MECH', 'how inclusive pronouns build common ground with an audience', _, _, _),
 ('C', 'DIST', 'persuasive force versus a ranting or accusing tone', _, _, _),
 ('C', 'APP', 'rewrite a supplied original accusing sentence in a measured, persuasive register', _, _, _),
 ('C', 'MISCON', 'a tone that slides into ranting or blaming the reader', _, _, 'MC-9093-2.4-04'),
]
F['2.5'] = [
 ('A', 'DEF', 'review: an informed judgement of a work, product, event or place, for readers deciding whether to try it', _, _, _),
 ('A', 'FEATURE', 'the sections of a review: introduction, account of what is reviewed, evaluation, verdict', _, _, _),
 ('A', 'PROC', 'planning a review: context, what it is, criteria, evidence for each, verdict', _, _, _),
 ('A', 'DIST', 'reviewing versus recounting', _, _, _),
 ('A', 'MISCON', 'recounting the experience in order instead of judging it', _, _, 'MC-9093-2.5-01'),
 ('A', 'MISCON', 'spending the words on minor or side details (the journey there, the snacks)', _, _, 'MC-9093-2.5-03'),
 ('B', 'DEF', 'criteria: the standards a review judges by', _, _, _),
 ('B', 'DEF', 'evidentiary logic: every judgement followed by the evidence that supports it', _, _, _),
 ('B', 'APP', 'support a supplied bare original judgement with two specific pieces of evidence', _, _, _),
 ('B', 'EVAL', 'judge whether a supplied original verdict is justified by the evidence given', _, _, _),
 ('B', 'MISCON', 'listing features or activities without evaluating any of them', _, _, 'MC-9093-2.5-02'),
 ('C', 'DEF', 'evaluative lexis', _, _, _),
 ('C', 'FEATURE', 'graded evaluative vocabulary, from adequate to outstanding and from disappointing to dire', _, _, _),
 ('C', 'APP', 'replace the vague evaluation in a supplied original sentence with precise evaluative lexis', _, _, _),
 ('C', 'DIST', 'a balanced verdict versus a list of likes and dislikes', _, _, _),
 ('C', 'MISCON', 'personal likes and dislikes offered with no criteria and no critique', _, _, 'MC-9093-2.5-04'),
]
F['2.6'] = [
 ('A', 'DIST', 'the precise word versus the general word', _, _, _),
 ('A', 'APP', 'replace the general words in a supplied original sentence with precise ones', _, _, _),
 ('A', 'APP', 'choose between three supplied near-synonyms for a supplied context, with the reason', _, _, _),
 ('A', 'FEATURE', 'what a range of language means: varied vocabulary, sentence structures and devices, all controlled', _, _, _),
 ('A', 'MISCON', 'ambitious vocabulary used in the wrong sense, or informality that slides into error', _, _, 'MC-9093-2.6-05'),
 ('B', 'WHY', 'why control comes before complexity', _, _, _),
 ('B', 'APP', 'split a supplied overlong original sentence into two clear ones', _, _, _),
 ('B', 'DIST', 'a varied range of sentences versus long sentences that lose control', _, _, _),
 ('B', 'MISCON', 'long complex sentences in which the grammar breaks down', _, _, 'MC-9093-2.6-03'),
 ('C', 'DEF', 'comma splice', _, _, _),
 ('C', 'APP', 'correct a supplied comma splice in three different ways', _, _, _),
 ('C', 'DIST', 'an accidental sentence fragment versus a deliberate minor sentence', _, _, _),
 ('C', 'FEATURE', 'how direct speech is punctuated and paragraphed', _, _, _),
 ('C', 'APP', 'correct the tense shifts in a supplied original passage of three sentences', _, _, _),
 ('C', 'APP', 'correct the capital letters in a supplied original passage with proper nouns', _, _, _),
 ('C', 'DIST', 'its versus it’s', _, _, _),
 ('C', 'DIST', 'their, there and they’re', _, _, _),
 ('C', 'PROC', 'proofreading: one read for each kind of error', _, _, _),
 ('C', 'MISCON', 'two sentences joined by a comma', _, _, 'MC-9093-2.6-01'),
 ('C', 'MISCON', 'tense that drifts between past and present', _, _, 'MC-9093-2.6-02'),
 ('C', 'MISCON', 'missing capital letters, and sentence fragments that are not deliberate', _, _, 'MC-9093-2.6-04'),
 ('C', 'MISCON', 'speech run into the narrative without its punctuation or new paragraphs', _, _, 'MC-9093-2.6-06'),
]

# ---------------------------------------------------------------------------- practice texts
# A text a task is answered from is an ORIGINAL written for the purpose (RS-48). Its length is the
# syllabus's (550-750 words, pages 19-20). The source types follow the corpus shares (analysis, section 3).
# (text_id, words_min, words_max, genre and subject)
_Q1 = [('news feature article', 'a school that turned its unused land into an urban farm'),
       ('opinion column', 'what a surge of tourism has done to a small coastal town'),
       ('memoir extract', 'a grandparent recalling a working life on the railways'),
       ('fiction extract', 'a river crossing that goes wrong during the rainy season'),
       ('blog post', 'a first solo hike through a mountain range'),
       ('travel writing', 'a traveller’s first day in a desert town'),
       ('magazine profile article', 'a teenage inventor and the device she built'),
       ('product review article', 'a solar-powered phone charger tested for a month'),
       ('autobiography extract', 'a musician remembering her first public performance'),
       ('news article', 'a town’s water-saving scheme in a drought year'),
       ('fiction extract', 'a busy market day seen through a stallholder’s eyes'),
       ('brochure text', 'a restored heritage steam railway and its day trips')]
_Q2 = [('magazine feature article', 'teenagers, sleep and the school day'),
       ('opinion article', 'whether a city should give its streets to cyclists'),
       ('fiction extract', 'a homecoming after years away'),
       ('fiction extract', 'a tense night drive on a mountain road'),
       ('blog post', 'a month lived without a smartphone'),
       ('memoir extract', 'learning to cook from a grandmother'),
       ('speech transcript', 'an address to a graduating class'),
       ('review', 'a newly opened science museum'),
       ('travel writing', 'a slow journey down a great river'),
       ('newspaper article', 'the rescue of a stranded young whale'),
       ('charity appeal', 'a campaign to put books in rural schools'),
       ('feature article', 'the history of a local football club')]
TEXTS = {
 '1.4': [('TXT-9093-1.4-%02d' % (n + 1), 550, 750, '%s: %s' % g) for n, g in enumerate(_Q1)],
 '1.5': [('TXT-9093-1.5-%02d' % (n + 1), 550, 750, '%s: %s' % g) for n, g in enumerate(_Q2)],
}

# ---------------------------------------------------------------------------- performance tasks
# Each task: item type, practice-text index or None, objective keys, assessment objectives, command word,
# tariff, Bloom level, brief, the task's AO marks (from the level table it models; corpus) and, for a
# second part, the index of the first part it is written about.
# Twelve of each paper task: equal practice marks on the six tasks reproduces the AS weights 15/45/40.


def T(itype, tix, keys, aos, cw, tar, bloom, brief, marks=None, pair=None):
    return {'item_type': itype, 'text': tix, 'keys': keys, 'aos': aos, 'command_word': cw, 'mark_tariff': tar,
            'blooms_level': bloom, 'brief': brief, 'ao_marks': marks or {}, 'pair': pair}


_FORMS_1A = [('speech', 'opening a school assembly, to students'),
             ('letter to the editor', 'from a resident who disagrees with the column'),
             ('diary entry', 'written as the memoir’s subject at the end of one working day'),
             ('report', 'for the regional safety officer, on what happened and what should change'),
             ('email', 'to a friend who plans to make the same journey'),
             ('leaflet', 'for the town’s visitor information office'),
             ('podcast script', 'introducing the inventor to listeners of a science podcast'),
             ('advertisement', 'for the manufacturer, in a magazine for young people'),
             ('review', 'of the performance, by a critic who was in the audience'),
             ('blog post', 'by a student whose family takes part in the scheme'),
             ('speech', 'by the stallholder to a town council meeting about the market’s future'),
             ('email', 'to the railway’s manager, proposing a school visit')]
P = {}
P['1.1'] = [T('short_answer', None, ['A', 'B', 'C', 'D', 'E'], ['AO1', 'AO3'], None, None, 'Analyse',
              'context analysis: an original extract of about 150 words (%s) written into the prompt; identify its form, audience, '
              'purpose and context, each with the words that show it, and state its overall effect' % g)
            for g in ('an opinion column', 'a charity leaflet', 'a travel blog', 'a letter of complaint')]
P['1.2'] = ([T('short_answer', None, ['A'], ['AO3'], None, None, 'Analyse',
               'word-level analysis: an original extract of about 120 words (%s) written into the prompt; identify and analyse three '
               'word-level features (word class, semantic field, figurative language, sound or word formation), each with evidence and effect' % g)
             for g in ('descriptive prose', 'an advertisement')] +
            [T('short_answer', None, ['B', 'C'], ['AO3'], None, None, 'Analyse',
               'grammatical analysis: an original extract of about 120 words (%s) written into the prompt; analyse its voice, tense or '
               'modality and its sentence structures, with evidence and effect' % g)
             for g in ('a news report', 'a first-person narrative')] +
            [T('short_answer', None, ['D', 'E', 'F', 'G'], ['AO3'], None, None, 'Analyse',
               'text-level analysis: an original text of about 150 words (%s) written into the prompt; analyse its structure, perspective, '
               'rhetoric and tone, with evidence and effect' % g)
             for g in ('a short speech', 'a short opinion blog')])
P['1.3'] = [T('short_answer', None, ['A', 'B', 'C', 'D'], ['AO1', 'AO3'], None, None, 'Analyse',
              'evidence paragraph: an original extract of about 150 words (%s) written into the prompt; write one analytical paragraph of '
              'about 120 words with at least three short embedded quotations; the model paragraph is the answer' % g)
            for g in ('a feature article', 'a memoir', 'a persuasive leaflet', 'a review')]
P['1.4'] = []
for n, (form, who) in enumerate(_FORMS_1A):
    P['1.4'].append(T('writing_task', n, ['A', 'C', 'D'], ['AO1', 'AO2'], None, 10, 'Create',
                      'Question 1(a)-style directed response, 150–200 words, as a %s %s, re-using the source’s content; model answer, '
                      'and guidance against both columns of the 10-mark table (reading /5, writing /5)' % (form, who),
                      {'AO1': 5, 'AO2': 5}))
    P['1.4'].append(T('source_analysis', n, ['E', 'F', 'G'], ['AO1', 'AO3'], 'Compare', 15, 'Analyse',
                      'Question 1(b)-style comparison of the model %s with the source, analysing form, structure and language; model '
                      'answer, and guidance against both columns of the 15-mark table (reading /5, analysis /10)' % form,
                      {'AO1': 5, 'AO3': 10}, pair=len(P['1.4']) - 1))
P['1.4'] += [T('short_answer', None, ['B'], ['AO2'], None, None, 'Create',
               'style-matching task: an original extract of about 100 words (%s) written into the prompt, to be continued for about '
               '80 words in the same style; the model continuation and a note of the features matched' % g)
             for g in ('a humorous column', 'a formal report')]
P['1.5'] = [T('source_analysis', n, ['A', 'B', 'C', 'D', 'E', 'F', 'G'], ['AO1', 'AO3'], 'Analyse', 25, 'Analyse',
              'Question 2-style text analysis of the practice text, focusing on form, structure and language; model answer, and '
              'guidance against both columns of the 25-mark table (reading /5, analysis /20)', {'AO1': 5, 'AO3': 20})
            for n in range(12)]
_FORMS_2A = [('speech', 'opening a class debate, introducing both sides'),
             ('speech', 'to parents at a school open evening, persuading them to support a new club'),
             ('email', 'to a cousin abroad, describing a festival you have just been to'),
             ('email', 'to a local business, asking it to sponsor a charity run'),
             ('story opening', 'for a school anthology, creating a sense of unease'),
             ('story opening', 'for a magazine competition, creating a sense of wonder'),
             ('blog post', 'about a skill you learned the hard way, encouraging others to try it'),
             ('blog post', 'describing a place in your town at dawn for visitors'),
             ('report', 'to the school board on how students use the library'),
             ('leaflet', 'encouraging households to cut food waste'),
             ('letter', 'to a newspaper, responding to a claim that young people do not read'),
             ('diary entry', 'on the evening of your first day in a new job')]
P['2.1'] = []
for n, (form, what) in enumerate(_FORMS_2A):
    P['2.1'].append(T('writing_task', None, ['A', 'B', 'C'], ['AO2'], None, 15, 'Create',
                      'Question 1(a)-style shorter writing, no more than 400 words: a %s %s, with the focus stated in the prompt; '
                      'model answer, and guidance against the 15-mark table' % (form, what), {'AO2': 15}))
    P['2.1'].append(T('source_analysis', None, ['D', 'E', 'F'], ['AO3'], None, 10, 'Analyse',
                      'Question 1(b)-style reflective commentary on the model %s: how its choices of form, structure and language fulfil '
                      'the brief; model answer quoting the model text, and guidance against the 10-mark table' % form,
                      {'AO3': 10}, pair=len(P['2.1']) - 1))
P['2.2'] = ([T('essay_plan', None, ['A', 'B', 'C', 'D', 'E'], ['AO2'], None, None, 'Create',
               'plan for a Section B-style %s task of 600–900 words: the shape, the sections with their word shares, the '
               'effect each section is for, and the ending' % g)
             for g in ('narrative', 'discursive', 'review')] +
            [T('short_answer', None, ['D', 'E'], ['AO2'], None, None, 'Apply',
               'paragraph-building task: %s written into the prompt, to be built into a developed, coherent paragraph; a model '
               'paragraph is the answer' % g)
             for g in ('four bare original notes on one point', 'an original undeveloped paragraph of about 60 words')])
P['2.3'] = [T('writing_task', None, keys, ['AO2'], None, 25, 'Create',
              'Section B-style %s, 600–900 words, %s; model answer and guidance against the 25-mark table' % (kind, what), {'AO2': 25})
            for kind, what, keys in (
             ('story', 'which must begin with an original sentence given in the prompt, creating a sense of suspense', ['A', 'B', 'D']),
             ('story', 'with the title of an original prompt, creating a sense of loss and recovery', ['A', 'B', 'D']),
             ('description', 'of a crowded place in the moments before an event begins, creating a sense of anticipation', ['C', 'D']),
             ('description', 'of a landscape as the weather changes, creating a sense of calm turning to threat', ['C', 'D']))]
P['2.4'] = [T('writing_task', None, ['A', 'B', 'C'], ['AO2'], None, 25, 'Create',
              'Section B-style %s, 600–900 words, %s; model answer and guidance against the 25-mark table' % (form, what), {'AO2': 25})
            for form, what in (('essay', 'for a class discussion, giving your view on whether homework should be abolished'),
                               ('magazine article', 'exploring whether social media has made friendships stronger or weaker'),
                               ('speech', 'to a youth forum, arguing for or against a ban on single-use plastics'),
                               ('letter to a newspaper', 'responding to a proposal to close a public library'))]
P['2.5'] = [T('writing_task', None, ['A', 'B', 'C'], ['AO2'], None, 25, 'Create',
              'Section B-style review, 600–900 words, %s; model answer and guidance against the 25-mark table' % what, {'AO2': 25})
            for what in ('of a one-day course you attended, for a website of courses',
                         'of a live performance, for an arts magazine',
                         'of a new sports centre, for a local news website',
                         'of a mobile app or television series, for a blog')]
P['2.6'] = ([T('short_answer', None, ['C'], ['AO2'], None, None, 'Apply',
               'proofreading task: an original paragraph of about 120 words with a stated number of errors of named kinds (%s), '
               'written into the prompt; the corrected paragraph is the answer' % g)
             for g in ('comma splices and capitals', 'tense and agreement', 'speech punctuation and paragraphing')] +
            [T('short_answer', None, ['A', 'B'], ['AO2'], None, None, 'Apply',
               'rewriting task: an original flat or overlong paragraph of about 100 words (%s), written into the prompt, to be '
               'rewritten with precise vocabulary and controlled, varied sentences; a model rewrite is the answer' % g)
             for g in ('a descriptive paragraph', 'an argument paragraph')])

# ------------------------------------------------------------------------------ misconceptions
# (id, topic, objective key, report tasks, theme, what learners do, the test that tells it apart, evidence pattern)
# The evidence pattern is matched against examiner-report sentences that record a weakness, filed by task
# (gen/er9093.py). The build counts the report variants that raise it; an entry with no evidence stops the build.
A1, B1, Q2, G1 = 'P1 1(a) directed response', 'P1 1(b) comparison', 'P1 2 text analysis', 'P1 general'
A2, B2, IM, DI, RV, G2 = ('P2 1(a) shorter writing', 'P2 1(b) reflective commentary', 'P2 B imaginative/descriptive',
                          'P2 B discursive/argumentative', 'P2 B review/critical', 'P2 general')
MISCONCEPTIONS = [
 ('MC-9093-1.1-01', '1.1', 'A', [B1], 'conventions listed, not analysed',
  'list the conventions of a form (headline, subheadings, paragraphs) as if naming them were the analysis',
  'for each convention, say what job it does for this reader; a convention with no job named has only been spotted',
  r"listed the conventions|mainly listed"),
 ('MC-9093-1.1-02', '1.1', 'C', [A1], 'the role or purpose the task sets',
  'write from a different point of view, or with a different purpose, from the one the task sets',
  'reread the task and name the speaker, the reader and the purpose before the first sentence; every paragraph should fit all three',
  r"perspective|rather than advising|dissuad|did not acknowledge"),
 ('MC-9093-1.1-03', '1.1', 'D', [B1], 'features tied to audience and purpose',
  'name the purpose and audience at the start and then analyse features without ever linking them back',
  'each analytical point should end by saying how the feature serves this text’s audience or purpose',
  r"relate to audience|related to audience"),
 ('MC-9093-1.1-04', '1.1', 'E', [A1, Q2], 'the source read accurately',
  'misread a detail of the source (who did what, what a phrase refers to) and build the answer on the mistake',
  'check each detail you use against the sentence it comes from; if you cannot point to the words, do not use the detail',
  r"misunderst|misread|did not realise|confuse the detail|misinterpret"),
 ('MC-9093-1.2-01', '1.2', 'A', [Q2], 'connotations analysed precisely',
  'say that a word has “positive” or “negative” connotations and stop',
  'name the specific association (danger, warmth, officialdom) and what it makes the reader feel about the subject; “positive” names neither',
  r"positive connotations|negative connotations"),
 ('MC-9093-1.2-02', '1.2', 'G', [Q2], 'frequency, formality and tone kept apart',
  'treat how common a word is, how formal it is, and the tone of the text as one idea',
  'ask three separate questions: is the word everyday or rare? is it formal or informal? what attitude does the text take? The answers can differ',
  r"higher and lower|frequency lexis|orders of lexis|referred to as tone"),
 ('MC-9093-1.2-03', '1.2', 'C', [Q2], 'sentence structure analysed for effect',
  'label sentences as simple, compound or complex and say nothing about what the structure does',
  'after the label, ask what the structure makes the reader notice or feel at that point; if the label could be deleted without loss, nothing was analysed',
  r"sentence types|simple or complex|syntax"),
 ('MC-9093-1.2-04', '1.2', 'E', [Q2], 'narrative and figurative terms used exactly',
  'use a term loosely, such as calling any first-person account stream of consciousness, or any image personification',
  'check the term’s definition in the glossary against the example; if the example lacks the defining feature, use the plainer term',
  r"stream of consciousness|personification"),
 ('MC-9093-1.2-05', '1.2', 'F', [B2, Q2], 'rhetorical questions identified correctly',
  'call every question rhetorical, and treat the rhetorical question as the only rhetorical device',
  'a rhetorical question expects no answer because the answer is assumed; if the text answers it, or the reader must, it is a real question',
  r"not rhetorical|only seen as .rhetorical question"),
 ('MC-9093-1.2-06', '1.2', 'A', [B2, Q2], 'features identified correctly',
  'name the wrong feature, such as a simile called a metaphor or an adjective called an adverb',
  'test the example against the definition before naming it; a wrong label undermines the point built on it',
  r"wrongly identified|incorrectly identified|incorrectly used|used incorrectly"),
 ('MC-9093-1.2-07', '1.2', 'D', [B2, Q2], 'structure analysed, not just located',
  'leave structure out of the analysis, or say where things are without saying what the arrangement does',
  'a structural point names the arrangement (an opening, a shift, a return) and its effect on the reader at that moment',
  r"little or no comment on structure|focused solely on (structure|language)"),
 ('MC-9093-1.3-01', '1.3', 'B', [Q2], 'short, precise quotation',
  'quote whole sentences, or cite a range of lines, instead of the words that carry the point',
  'a quotation is the right length when every word in it is one you go on to comment on',
  r"quoting at|range of lines|lengthy quot|long quot"),
 ('MC-9093-1.3-02', '1.3', 'A', [B1, B2], 'every point supported by the text',
  'make analytical points with no words quoted from the texts',
  'every point needs the words that prove it; a point you cannot quote for is an impression, not analysis',
  r"few or no supporting|without (any )?(supporting )?(evidence|examples)|lacked exemplification|did not provide (specific )?(evidence|examples)|failed to provide evidence|without providing examples"),
 ('MC-9093-1.3-03', '1.3', 'C', [Q2, B2], 'precise comment on effect',
  'follow each quotation with a stock phrase (“this engages the reader”, “this creates a picture”) that could follow any quotation',
  'a precise comment could only be written about this quotation; if it fits any other, it says nothing about this one',
  r"general phrases|vague phrase|makes the reader|reader want|generalised"),
 ('MC-9093-1.3-04', '1.3', 'D', [Q2], 'points built into an argument',
  'write a string of separate observations with nothing joining them into a view of the text',
  'read the first sentence of each paragraph in turn; together they should state an argument about the whole text',
  r"haphazard|repetitive comments|random"),
 ('MC-9093-1.4-01', '1.4', 'A', [A1], 'the source re-used, not lifted',
  'copy phrases and sentences from the source into the directed response',
  'the content should come from the source; the sentences should be yours, in the register of the new form',
  r"lift|quoted large|quote(d)? .{0,20}large amounts|copied|too much of the extract"),
 ('MC-9093-1.4-02', '1.4', 'A', [A1], 'the source reshaped for the new form',
  'summarise the source in order, instead of selecting from it and reshaping it for the new audience and purpose',
  'a directed response is organised by what its own reader needs; if its order matches the source’s paragraph by paragraph, it is a summary',
  r"summar|listing information|shape it to the requirements"),
 ('MC-9093-1.4-03', '1.4', 'D', [A1], 'the 150–200-word range kept',
  'write far more, or far less, than 150–200 words',
  'count before you finish: well outside the range, the response is a poorer fit to its form and purpose, and 1(b) time is lost',
  r"considerably (longer|shorter)|word (limit|count)|150|200 words"),
 ('MC-9093-1.4-04', '1.4', 'A', [A1], 'content kept to what the source supports',
  'add material the source does not contain, until the response tells a different story',
  'every idea in the response should trace back to the source; new material has no source to compare against in 1(b)',
  r"new material|different narrative|loss of focus|extraneous|introduce"),
 ('MC-9093-1.4-05', '1.4', 'D', [A1], 'the form’s conventions used',
  'leave out the conventions the form needs, such as a speech with no address to its audience or a letter with no salutation',
  'before writing, list the three conventions a reader of this form would miss if they were absent, and use them',
  r"convention|salutation|valediction|headline|sign.off"),
 ('MC-9093-1.4-06', '1.4', 'E', [B1], 'both texts analysed, including your own',
  'write mostly about the source and little or nothing about your own response',
  'count the quotations from each text; a comparison needs evidence from both, in roughly equal measure',
  r"focused more|occasionally entirely"),
 ('MC-9093-1.4-07', '1.4', 'E', [B1], 'writing compared, not content',
  'compare what the two texts say instead of how they are written',
  'each comparative point should name a choice of form, structure or language in each text; “both talk about” compares content',
  r"comparison of content|summari[sz]e content|neglected language"),
 ('MC-9093-1.4-08', '1.4', 'G', [B1], 'comparison sustained throughout',
  'discuss the source and then your own text, with no reference across between them',
  'every paragraph should mention both texts; a paragraph that could be cut out and read alone has stopped comparing',
  r"in turn|ongoing referenc|comparative requirement|limited comparison|minimal comparison|little comparison"),
 ('MC-9093-1.4-09', '1.4', 'F', [B1], 'tone traced to its language',
  'name a tone (humorous, urgent) without pointing to the words that create it',
  'a tone is a result; point to the choices that produce it, or the claim cannot be checked',
  r"tone unconnected|broad identification of tone|language use creates tone"),
 ('MC-9093-1.5-01', '1.5', 'C', [Q2], 'analysis, not summary',
  'retell or summarise the text, often at length, instead of analysing it',
  'if a paragraph could be written by someone who had not noticed a single choice the writer made, it is summary',
  r"summari[sz]e the contents?|paraphras|retell"),
 ('MC-9093-1.5-02', '1.5', 'F', [Q2], 'organised by argument, not by paragraph order',
  'work through the text paragraph by paragraph, or jump around it with no line of argument',
  'plan by effect or purpose first; the text’s paragraph order should not be your paragraph order',
  r"paragraph.by|in the … paragraph|haphazard"),
 ('MC-9093-1.5-03', '1.5', 'E', [Q2], 'features analysed, not spotted',
  'name devices and sentence types one after another without saying what any of them does',
  'delete the name of the feature from your sentence; if nothing about meaning or effect is left, nothing was analysed',
  r"feature.spotting"),
 ('MC-9093-1.5-04', '1.5', 'B', [Q2], 'a coherent whole-text view',
  'describe the style in general terms that are never proved by an example, or analyse details that never add up to a view of the whole',
  'the introduction should state a view of the whole text that the rest proves; a view with no proof, or proof with no view, is half an analysis',
  r"coherent|whole.text"),
 ('MC-9093-1.5-05', '1.5', 'A', [Q2], 'the writing analysed, not the topic',
  'respond to the topic (agree with it, explain the subject, add opinions) instead of analysing how the text is written',
  'every sentence of the answer should be about the writer’s choices; a sentence about the subject itself belongs to a different task',
  r"distract|focused on aspects of the passage|affirmative agreement"),
 ('MC-9093-2.1-01', '2.1', 'B', [A2], 'the 400 words used',
  'write far less than the space allows, so that nothing is developed',
  'a response well under half the limit rarely has room to develop the brief; plan three developed sections before writing',
  r"under 200|fewer than 200|did not fully utilise|were short|very short|very brief"),
 ('MC-9093-2.1-02', '2.1', 'A', [A2], 'the form the brief sets',
  'write in a different form from the one set, such as a story where a description or a speech was asked for',
  'read your opening and closing lines alone; they should tell a reader which form this is and who it is for',
  r"required form|purely narrative|slip(ped)? into narrative|read more like|first-person narrative|narrative in terms of form"),
 ('MC-9093-2.1-03', '2.1', 'A', [A2], 'the role and occasion the brief sets',
  'ignore the role or the occasion the brief sets, such as a debate speech that never opens the debate',
  'name who is speaking, to whom, on what occasion; the first paragraph should make all three clear',
  r"did not address their role|did not acknowledge|launching straight|welcoming the audience|introducing the debate"),
 ('MC-9093-2.1-04', '2.1', 'A', [A2], 'the focus the prompt adds',
  'miss the extra focus the prompt adds, such as persuading without reasons or encouraging without enthusiasm',
  'underline the prompt’s focus sentence; at the end, point to where each part of it is achieved',
  r"without elaborating|did not encourage|lacked enthusiasm|concrete reasons|token"),
 ('MC-9093-2.1-05', '2.1', 'E', [B2], 'the commentary quotes the text',
  'write a commentary that never quotes the text it is about',
  'every point in a commentary needs a short quotation from your 1(a); without it the commentary is a list of intentions',
  r"few or no supporting|without (any )?(supporting )?(evidence|examples)|lacked exemplification|did not provide (specific )?(evidence|examples)|failed to provide evidence|without providing examples"),
 ('MC-9093-2.1-06', '2.1', 'D', [B2], 'choices analysed, not content retold',
  'retell the content of your own piece instead of analysing its choices',
  'a commentary sentence names a choice and what it does for the brief; a sentence that says what happens in your text is content',
  r"paraphrased|content of their piece|focused entirely on content|general commentary on the content"),
 ('MC-9093-2.1-07', '2.1', 'F', [B2], 'form, structure and language all covered',
  'comment on structure alone, or on language alone',
  'check the commentary has at least one point each on form, structure and language before it ends',
  r"little or no comment on structure|focused solely on|solely on"),
 ('MC-9093-2.1-08', '2.1', 'E', [B2], 'features explained, not listed',
  'list the features used (“I used adjectives, metaphors and alliteration”) and stop',
  'a named feature needs its example and its effect on the reader; a list of feature names answers no part of the task',
  r"listed linguistic features|identif\w+ (some|a few) basic|stopped short|simple identification|without any supporting evidence"),
 ('MC-9093-2.2-01', '2.2', 'D', [IM, DI, RV, G2], 'paragraphs that organise',
  'write without paragraphs, or break paragraphs at random',
  'each paragraph should have one job you can name in a few words; if you cannot name it, the break is in the wrong place',
  r"lack(ed|ing|s)? paragraph|lacked paragraphs|minimal attempt at organisation|lack of structure|clear paragraphing"),
 ('MC-9093-2.2-02', '2.2', 'B', [IM, DI], 'a real ending',
  'end abruptly, or rush the ending, so the piece stops rather than finishes',
  'an ending resolves or deliberately leaves open what the piece set up; a stop just runs out of words or time',
  r"abrupt|rushed|conclusions were weak|ending"),
 ('MC-9093-2.2-03', '2.2', 'C', [G2, IM, DI, RV], 'the 600–900 words reached',
  'write well short of 600 words, often because Section A took too long',
  'plan the time before starting: Section B carries half the paper’s marks and needs half its time',
  r"fewer than 400|under 600|word count|required word count|fewer than 600"),
 ('MC-9093-2.3-01', '2.3', 'D', [IM], 'description, not story',
  'let a description turn into a story told as a sequence of events',
  'if the paragraphs are ordered by “and then”, it is narrating; a description is ordered by what is noticed',
  r"narrative approach|narration was common|narrative details|describing a journey|journey|more narrative"),
 ('MC-9093-2.3-02', '2.3', 'A', [IM, A2], 'a contained, credible plot',
  'pack in so many events and characters, or such unlikely ones, that the story has no credible shape',
  'in 600–900 words, one conflict, developed, carries a story further than several summarised',
  r"elaborate plots|many characters|unrealistic|narrative control"),
 ('MC-9093-2.3-03', '2.3', 'C', [IM], 'precise detail, not piled adjectives',
  'stack adjectives in front of nouns in place of one precise detail',
  'cut every adjective you could swap for another without loss; what remains should be the detail only this scene has',
  r"lots of adjectives|string of adjectives|adjectives|overwritten|clich"),
 ('MC-9093-2.3-04', '2.3', 'B', [IM, G2], 'the effect the question asks for',
  'tell a story that never creates the effect the question names (drama, suspense, mystery)',
  'name the effect, then point to the moments built to create it; if none were built for it, the task is only half done',
  r"sense of drama|suspense|anticipation"),
 ('MC-9093-2.3-05', '2.3', 'D', [IM], 'the given sentence used',
  'leave out, or change, the sentence the question says the story must begin or end with',
  'copy the given sentence exactly where the question puts it, and make the story grow from it or towards it',
  r"did not begin with|sentence provided|given sentence|opening sentence"),
 ('MC-9093-2.3-06', '2.3', 'A', [IM], 'dialogue that earns its place',
  'use long stretches of dialogue that carry no story and are badly punctuated',
  'keep a line of speech only if it reveals character or moves the plot; set it out with its punctuation and a new line for each speaker',
  r"dialogue"),
 ('MC-9093-2.4-01', '2.4', 'A', [DI], 'more than one side weighed',
  'write a one-sided list of reasons that ends in a one-line conclusion',
  'a discursive piece gives the other side its strongest form before answering it; a list of reasons for one side is not a discussion',
  r"one-sided|list of reasons|no consideration of opinions|balanced|counter"),
 ('MC-9093-2.4-02', '2.4', 'B', [DI], 'points developed, not repeated',
  'repeat the same point in new words instead of developing it',
  'each new paragraph should add a reason, an example or a consequence the earlier ones did not',
  r"recycled|repetitive|same point|repeated ideas|underdeveloped|vague points"),
 ('MC-9093-2.4-03', '2.4', 'A', [DI], 'the whole issue addressed',
  'narrow a broad issue to one aspect of it, such as technology alone in a question about modern life',
  'list the issue’s main aspects before planning; the answer should reach at least three',
  r"one aspect|narrow"),
 ('MC-9093-2.4-04', '2.4', 'C', [DI], 'persuasive force without ranting',
  'let the tone slide into ranting or blaming the reader',
  'read the piece as its named audience; if you would feel accused rather than persuaded, the tone has turned against the purpose',
  r"accusatory|rant|bemoan"),
 ('MC-9093-2.4-05', '2.4', 'A', [DI], 'the form set, not a neighbouring one',
  'write in the wrong form, such as an article with a headline and subheadings when an essay was set',
  'check the form word in the task before planning; an essay has no headline, an article does',
  r"essay nature|correct form|headline and subheadings"),
 ('MC-9093-2.5-01', '2.5', 'A', [RV], 'judging, not recounting',
  'recount the experience in the order it happened instead of judging it',
  'a review paragraph is ordered by a criterion, and says how well something met it; a paragraph ordered by “then” is a recount',
  r"recounted|recount|narration|narrative|described the whole experience"),
 ('MC-9093-2.5-02', '2.5', 'B', [RV], 'features evaluated, not listed',
  'list features, activities or selling points without evaluating any of them',
  'after each feature, ask: how good was it, compared with what, and why does that matter to the reader?',
  r"list(ed)? (the )?(activities|selling points|content|aspects|and describe)|without (then )?developing|not further|selling points"),
 ('MC-9093-2.5-03', '2.5', 'A', [RV], 'the main things judged',
  'spend the words on minor or side details, such as the journey there or the snacks',
  'rank what a reader deciding whether to go most needs to know; the top items get the most words',
  r"minor detail|substantial issues|journey to|too long|irrelevant"),
 ('MC-9093-2.5-04', '2.5', 'C', [RV, G2], 'criteria and critique, not likes',
  'offer personal likes and dislikes with no criteria and no critique',
  'a judgement names the standard it uses; “I liked it” names none, “the pacing held attention to the last scene” names one',
  r"personal likes|critique|personal opinion"),
 ('MC-9093-2.6-01', '2.6', 'C', [G2, A2], 'sentence boundaries marked',
  'join two complete sentences with a comma',
  'if both sides of the comma could stand alone as sentences, a comma alone cannot join them',
  r"commas instead of full stops|commas rather than full stops|comma splice|separating sentences with commas"),
 ('MC-9093-2.6-02', '2.6', 'C', [G2, IM, A1], 'tense controlled',
  'let the tense drift between past and present',
  'choose the tense of the telling once, and check each verb against it',
  r"tense"),
 ('MC-9093-2.6-03', '2.6', 'B', [G2, A1], 'control before complexity',
  'write long complex sentences in which the grammar breaks down',
  'read each long sentence aloud; if you lose track of its subject before the end, split it',
  r"lose control of grammar|loss of grammatical control|long, complex sentences"),
 ('MC-9093-2.6-04', '2.6', 'C', [G2], 'capitals and complete sentences',
  'leave out capital letters for sentence openings and proper nouns, or write fragments that are not deliberate',
  'check every sentence opening and every name; a fragment is kept only if you can say what effect it is for',
  r"capital letters|fragments"),
 ('MC-9093-2.6-05', '2.6', 'A', [A1, A2], 'ambition within control',
  'reach for ambitious vocabulary in a sense it does not have, or let an informal style slide into errors',
  'a plainer word used exactly beats an impressive one used wrongly; informal register is still accurate English',
  r"over.ambitious|overly informal|informality"),
 ('MC-9093-2.6-06', '2.6', 'C', [G2], 'speech set out correctly',
  'run speech into the narrative without its punctuation or new paragraphs',
  'each new speaker gets a new line; the spoken words sit inside the speech marks with their own punctuation',
  r"direct speech"),
]

# ------------------------------------------------------------------------------------- glossary
GLOSSARY = [
 # the tasks
 ('directed response', 'A new text written from a source text for a form, audience and purpose the task sets, re-using the source’s content.', 'Not a summary of the source, and not a copy of its wording.'),
 ('comparison', 'An analysis of the similarities and differences between two texts, each explained by the texts’ purposes, audiences and contexts.', 'In Paper 1 Question 1(b) the two texts are the source and your own directed response.'),
 ('text analysis', 'A structured account of how a text’s form, structure and language make meaning for its audience.', None),
 ('shorter writing', 'The Paper 2 Question 1(a) task: a text of no more than 400 words written to a brief.', None),
 ('reflective commentary', 'An analysis of your own text’s choices of form, structure and language and how they fulfil the brief.', 'It analyses choices; it does not retell what your text says.'),
 ('extended writing', 'The Paper 2 Section B task: one continuous piece of 600–900 words in one of three categories.', None),
 ('brief', 'The specification a piece of writing must meet: its form, audience, purpose, role and any focus the prompt adds.', None),
 # form, audience, purpose, context
 ('form', 'The kind of text a piece is, such as an article, a speech, an email or a review, with the conventions its readers expect.', 'In grammar, “form” can also mean the shape of a word; in this subject it means the kind of text unless a block says otherwise.'),
 ('conventions', 'The features readers expect of a form, such as a headline in an article or a salutation in a letter.', None),
 ('genre', 'A family of texts grouped by shared purpose and conventions.', 'Wider than form: travel writing is a genre that can take the form of a blog, an article or a book.'),
 ('audience', 'The readers or listeners a text is designed for, stated or implied.', None),
 ('implied reader', 'The reader a text’s choices assume, who may differ from the people who actually read it.', None),
 ('purpose', 'What a text sets out to do, such as inform, persuade, entertain, advise or argue; many texts have more than one.', None),
 ('context', 'The situation a text is produced and read in: when, where, by whom, for whom and through what medium.', 'In analysis it can also mean the words around a quotation; say which sense you mean.'),
 ('characteristic features', 'The features that make a text recognisably the kind of text it is.', None),
 ('style', 'The overall manner of a text, produced by its choices of form, structure and language together.', 'Distinct from tone, which is the attitude a text conveys.'),
 ('non-fiction', 'Writing that presents itself as true: articles, memoirs, reviews, speeches, letters, travel writing.', 'Non-fiction can use narrative techniques without becoming fiction.'),
 # language: words
 ('word class', 'The grammatical category of a word by the job it does: noun, verb, adjective, adverb, pronoun, determiner, preposition, conjunction.', 'Also called parts of speech.'),
 ('noun', 'A word that names a person, place, thing or idea.', None),
 ('concrete noun', 'A noun for something that can be perceived by the senses.', None),
 ('abstract noun', 'A noun for an idea, quality or state.', None),
 ('verb', 'A word for an action, a process or a state.', None),
 ('adjective', 'A word that describes or modifies a noun.', None),
 ('adverb', 'A word that modifies a verb, an adjective, another adverb or a whole clause.', None),
 ('pronoun', 'A word that stands in for a noun phrase, such as she, we, they or it.', 'Inclusive pronouns (we, us) place writer and reader on the same side.'),
 ('determiner', 'A word that introduces a noun and specifies it, such as the, a, this or every.', None),
 ('modifier', 'A word or phrase that adds detail to another; a premodifier comes before a noun, a postmodifier after it.', None),
 ('lexis', 'The vocabulary of a text, and the choices a writer makes from it.', None),
 ('semantic field', 'A group of words in a text from one area of meaning, such as war or illness.', 'Also called a lexical field.'),
 ('denotation', 'The literal, dictionary meaning of a word.', None),
 ('connotation', 'The associations a word carries beyond its literal meaning.', 'Analysis names the specific association, not only whether it is favourable.'),
 ('figurative language', 'Language that means more than, or other than, its literal sense.', None),
 ('metaphor', 'A figure that describes one thing as if it were another, without “like” or “as”.', None),
 ('simile', 'A comparison of one thing with another using “like” or “as”.', None),
 ('personification', 'Giving human qualities or actions to something that is not human.', 'Not every vivid image is personification: it needs a human quality.'),
 ('pathetic fallacy', 'Weather or surroundings described so that they mirror a character’s feelings or a mood.', None),
 ('imagery', 'Language that creates a picture or sensation in the reader’s mind, literal or figurative.', None),
 ('phonology', 'The sound of language; in a written text, patterns such as alliteration, assonance, sibilance and onomatopoeia.', None),
 ('alliteration', 'Repetition of the same consonant sound at the start of nearby words.', None),
 ('sibilance', 'Repetition of hissing s and sh sounds.', None),
 ('onomatopoeia', 'A word whose sound imitates what it names.', None),
 ('morphology', 'How words are built from smaller parts: roots, prefixes, suffixes, compounds and coinages.', None),
 ('coinage', 'A newly made word, often a compound, used for effect.', None),
 # language: grammar and sentences
 ('voice (grammatical)', 'Whether a clause is active (the doer is the subject) or passive (the thing acted on is the subject).', 'Not the same as a writer’s voice: see “voice (writer’s)”.'),
 ('voice (writer’s)', 'The sense of a particular person speaking, carried by what they notice and how they say it.', 'Not grammatical voice.'),
 ('passive voice', 'A construction in which the thing acted on becomes the subject, and the doer is moved to a “by” phrase or left out.', None),
 ('aspect', 'How a verb presents an action in time: progressive (ongoing, “was running”) or perfect (completed, “has run”).', None),
 ('tense', 'The form of a verb that places an action in past or present time.', 'The present tense can narrate past events for immediacy.'),
 ('modality', 'The expression of certainty, possibility, obligation or permission, through modal verbs (may, must, could) and adverbs (perhaps, certainly).', 'High modality sounds sure; low modality sounds tentative.'),
 ('syntax', 'The arrangement of words, phrases and clauses in a sentence.', None),
 ('simple sentence', 'A sentence with one main clause.', None),
 ('compound sentence', 'Two or more main clauses joined by a coordinating conjunction such as and, but or so.', None),
 ('complex sentence', 'A sentence with a main clause and at least one subordinate clause.', None),
 ('minor sentence', 'A deliberate sentence without a main verb, used for effect.', 'Distinct from an accidental fragment.'),
 ('fronting', 'Moving a word or phrase to the start of a sentence to give it prominence.', None),
 ('tricolon', 'A group of three parallel words, phrases or clauses.', 'Also called a list of three or a triad.'),
 # the whole text
 ('structure', 'How a whole text is organised: its opening, sequence, shifts of focus, paragraphing and ending.', 'Sentence structure is a feature of language; “structure” alone means the whole text.'),
 ('cohesion', 'The ties that link sentences and paragraphs, such as discourse markers, reference and repetition.', None),
 ('discourse marker', 'A word or phrase that signals how a text moves on, such as however, meanwhile or in short.', None),
 ('anaphoric reference', 'A word that points back to something already mentioned, such as “this” or “she”.', None),
 ('cataphoric reference', 'A word that points forward to something not yet named.', None),
 ('cyclical structure', 'A structure in which the ending returns to the opening.', None),
 ('narrative perspective', 'The position from which a story or account is told: first person, second person, or third person limited or omniscient.', None),
 ('first-person narration', 'Telling from inside, as “I”, limited to what that narrator knows.', 'Not the same as stream of consciousness.'),
 ('stream of consciousness', 'Narration that follows a mind’s flow of thoughts and associations without ordinary ordering.', 'Rare in the papers; do not use it for ordinary first-person writing.'),
 ('omniscient narration', 'Third-person narration that can enter any character’s mind and know anything.', None),
 ('rhetorical device', 'A technique of persuasive language, such as a rhetorical question, anaphora, antithesis, tricolon or direct address.', None),
 ('rhetorical question', 'A question asked for effect, whose answer is assumed rather than sought.', 'A question the text goes on to answer, or that the reader must answer, is not rhetorical.'),
 ('direct address', 'Speaking to the reader or listener as “you”.', None),
 ('anaphora', 'Repetition of a word or phrase at the start of successive clauses or sentences.', 'In grammar, “anaphoric reference” is a different idea.'),
 ('antithesis', 'Opposed ideas placed side by side in parallel form.', None),
 ('hyperbole', 'Deliberate exaggeration.', None),
 ('tone', 'The attitude a text conveys towards its subject or its reader, such as urgent, wry or reassuring.', 'Tone is a result of choices; name the choices that create it.'),
 ('register', 'The variety of language suited to a situation, marked chiefly by its formality and its vocabulary.', 'Distinct from tone: a text can be formal in register and warm in tone.'),
 ('formality', 'How far a text’s language follows the conventions of formal, public usage rather than casual, private usage.', 'Not the same as how common or rare a word is.'),
 ('pragmatics', 'The study of meaning that comes from context and implication, not from the words alone.', None),
 ('implicature', 'What a speaker or writer implies without stating it.', None),
 # evidence and analysis
 ('evidence', 'The exact words from a text that show the feature a point is about.', None),
 ('embedded quotation', 'A short quotation worked into the grammar of your own sentence.', None),
 ('effect', 'What a choice leads the reader to think, feel or do.', 'Distinct from the meaning of the words.'),
 ('feature-spotting', 'Naming features without analysing what they do.', None),
 # writing
 ('topic sentence', 'The sentence, usually first, that states what a paragraph is about.', None),
 ('development', 'The detail, example or explanation that carries a point or a moment further.', None),
 ('Freytag’s Pyramid', 'A model of plot in five stages: exposition, rising action, climax, falling action, resolution.', None),
 ('exposition', 'The opening stage of a story, which sets out the situation, the characters and the setting.', None),
 ('climax', 'The point of greatest tension in a story, where the conflict comes to a head.', None),
 ('resolution', 'How a story’s conflict is settled, or deliberately left open, after the climax.', None),
 ('suspense', 'Tension created by making the reader wait to learn what will happen.', None),
 ('descriptive writing', 'Writing that builds a picture of a place, moment or experience from detail, not from a sequence of events.', None),
 ('narrative writing', 'Writing that tells a story: characters, a sequence of events and a change.', None),
 ('discursive writing', 'Writing that explores an issue from more than one side before reaching a view.', None),
 ('argumentative writing', 'Writing that argues for one position, answering the other side on the way.', None),
 ('dialectical structure', 'An argument built from a view (thesis), its opposite (antithesis) and a reasoned resolution (synthesis).', None),
 ('counterargument', 'A point against your position.', None),
 ('rebuttal', 'An answer to a counterargument that shows why it does not outweigh your case.', None),
 ('concession', 'Granting that part of an opposing point is true.', None),
 ('review', 'An informed judgement of a work, product, event or place, for readers deciding whether to try it.', None),
 ('criteria', 'The standards a review judges by, such as value, quality or suitability.', None),
 ('evidentiary logic', 'The link between a judgement and the specific evidence that supports it.', None),
 ('evaluative lexis', 'Vocabulary that expresses a judgement, from mild to strong.', None),
 ('comma splice', 'Two complete sentences joined by a comma alone.', None),
]

VARIANT_REGISTER = [
 {'term': 'imaginative/descriptive', 'variants': ['narrative', 'descriptive'],
  'consequence': 'The two ask for different content: a story with a conflict and a change, or a picture built from detail with no plot.',
  'teach_as': 'Wherever the category is taught or set, say which variant is meant and what that variant needs.'},
 {'term': 'discursive/argumentative', 'variants': ['discursive', 'argumentative'],
  'consequence': 'A discursive piece explores more than one side before reaching a view; an argumentative piece argues one position and answers the other side.',
  'teach_as': 'Wherever the category is taught or set, say which variant the task wording signals.'},
]

CONDITIONED = [
 {'mechanism_id': 'CM-9093-SHORT-SENTENCE',
  'name': 'Short sentences create tension or emphasis',
  'rationale': 'A short sentence creates emphasis or tension by contrast with the sentences around it. Taught as a rule on '
               'its own, it produces analyses that say every short sentence builds tension.',
  'asserted_when': [r'\bshort sentences?\b', r'\b(tension|suspense|emphasis|impact|drama)\b', r'\b(creates?|builds?|adds?|gives?)\b'],
  'required_conditions': [{'name': 'the contrast with the surrounding sentences',
                           'any_of': [r'\bcontrast', r'\blonger\b', r'\blong sentences?\b', r'\bvar(y|ied|iety|ying)\b',
                                      r'\bafter\b', r'\bamong\b', r'\bsurround']}]},
 {'mechanism_id': 'CM-9093-FORMAL-REGISTER',
  'name': 'A formal register is the correct one',
  'rationale': 'Register is right or wrong only for an audience and a purpose. A blog or a speech to classmates written '
               'formally is as mismatched as a report to officials written casually.',
  'asserted_when': [r'\bformal\b', r'\bregister\b', r'\b(should|must|always|correct|appropriate|right)\b'],
  'required_conditions': [{'name': 'the audience or purpose that decides it',
                           'any_of': [r'\baudience\b', r'\bpurpose\b', r'\breader', r'\blistener', r'\bwho\b', r'\bsituation\b']}]},
 {'mechanism_id': 'CM-9093-RHETORICAL-QUESTION',
  'name': 'Rhetorical questions engage the reader',
  'rationale': 'A rhetorical question works by making its audience supply an answer the writer wants. Stated without what '
               'answer it invites, the claim fits every question and analyses none.',
  'asserted_when': [r'\brhetorical questions?\b', r'\b(engages?|involves?|hooks?|draws? in|makes? the reader think)\b'],
  'required_conditions': [{'name': 'the answer the question invites, or the view it steers towards',
                           'any_of': [r'\banswer', r'\bassum', r'\bagree', r'\bview\b', r'\bconclu', r'\bsteer', r'\bimpl']}]},
]

# Constructs the AS learner does not sit (their route is components 12 and 22). The strings are scanned for
# in learner-facing text by C-11, so they are short terms, not sentences.
NOT_IN_ROUTE = ['Paper 3', 'Paper 4', 'language change', 'child language acquisition', 'English in the world',
                'language and the self', 'n-gram', 'phonemic transcription']
