# -*- coding: utf-8 -*-
"""Write PLAN-9093 and HANDOVER-9093 from the files build_9093.py wrote. Regenerate, never edit."""
import collections, datetime, json, os, sys
HOME = os.path.expanduser('~')
REPO = os.path.join(HOME, 'mnt', 'YYeni Study Resources')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from design_9093 import CODE, SLUG, WS_NAME, TOPICS, NOT_IN_ROUTE, UNITS, CONDITIONED  # noqa: E402
WS = os.path.join(REPO, 'work', WS_NAME)
REL = 'work/' + WS_NAME
J = lambda rel: json.load(open(os.path.join(WS, rel)))
FACTS, FW, SH, MC, REG = (J('curriculum/syllabus-facts.json'), J('curriculum/assessment-framework.json'),
                          J('curriculum/answer-shapes.json')[CODE]['tasks'], J('curriculum/misconceptions.json'),
                          J('curriculum/objective_registry.json'))
SYSF = json.load(open(os.path.join(HOME, 'mine', 'out', '9093_systemic.json')))
N_THR = len(json.load(open(os.path.join(HOME, 'mine', 'out', '9093_thresholds.json')))['rows'])
WO = {t['id']: J('topics/%s/work_order.json' % t['id']) for t in TOPICS}
CT = {t['id']: J('topics/%s/contract.json' % t['id']) for t in TOPICS}
TODAY = datetime.date.today().strftime('%-d %B %Y')
ANALYSIS = 'operations/analysis/%s-%s-corpus-analysis.md' % (CODE, SLUG)
BRIEF = '%s/SYLLABUS-BRIEF-%s-%s.md' % (REL, CODE, SLUG)
PLAN = 'PLAN-%s-%s.md' % (CODE, SLUG)
HAND = 'HANDOVER-%s-%s.md' % (CODE, SLUG)
ORDER = [t['id'] for t in TOPICS]
N = {'flash': sum(w['planned_flashcards'] for w in WO.values()), 'perf': sum(w['planned_performance_tasks'] for w in WO.values()),
     'texts': sum(len(w['practice_texts']) for w in WO.values()),
     'tw': (sum(x['words_min'] for w in WO.values() for x in w['practice_texts']), sum(x['words_max'] for w in WO.values() for x in w['practice_texts'])),
     'nw': (sum(c['depth_constraints']['word_budget']['min'] for c in CT.values()), sum(c['depth_constraints']['word_budget']['max'] for c in CT.values())),
     'obj': sum(len(t['objectives']) for t in TOPICS)}
N['items'] = N['flash'] + N['perf']
BL = collections.Counter(s['blooms_level'] for w in WO.values() for s in w['item_slots'] + w['performance_tasks'])
BLM = collections.Counter()
for w in WO.values():
    for s in w['performance_tasks']:
        BLM[s['blooms_level']] += s['mark_tariff'] or 0
ST = collections.Counter(s['subtype'] for w in WO.values() for s in w['item_slots'])
fmt = lambda n: format(n, ',')
thr = FW['grade_thresholds']
aob = FW['ao_mark_budget']
med = thr['median_minimum_marks']

# =================================================================================== PLAN
P = []
a = P.append
a('# Plan — Cambridge International AS Level English Language 9093')
a('')
a('Syllabus for 2024, 2025 and 2026, version 2 · route: AS Level, components 12 (Paper 1 Reading) and 22 (Paper 2 Writing) · first paper %s · plan generated %s' % (FACTS['first_exam'], TODAY))
a('')
a('This is the authoring brief for 9093 at AS and nothing else. It stands on two earlier steps: step zero, the syllabus (`%s`, with every value in `%s/curriculum/syllabus-facts.json` carrying its page and the verbatim line), and step one, the corpus analysis (`%s`), which read the 68 AS question papers and mark schemes from March 2021 to November 2025 and 9 examiner reports. Where a value below comes from the corpus or from our judgement, it says so.' % (BRIEF, REL, ANALYSIS))
a('')
a('**The job:** %d topics, %d objectives, **%s items** (%s flashcards, %s performance tasks), %d original practice texts of %s–%s words, and %s–%s words of notes.' % (len(TOPICS), N['obj'], fmt(N['items']), fmt(N['flash']), fmt(N['perf']), N['texts'], fmt(N['tw'][0]), fmt(N['tw'][1]), fmt(N['nw'][0]), fmt(N['nw'][1])))
a('')
a('---')
a('')
a('## 0. What the syllabus says')
a('')
a('| | | source |')
a('|---|---|---|')
a('| AO1 read and demonstrate understanding of a wide variety of texts | 15% of the AS Level | syllabus, p11 |')
a('| AO2 write effectively, creatively, accurately and appropriately, for a range of audiences and purposes | 45% | syllabus, p11 |')
a('| AO3 analyse the ways in which writers’ and speakers’ choices of form, structure and language produce meaning and style | 40% | syllabus, p11 |')
a('| AO4, AO5 | 0% at AS; Papers 3 and 4 only | syllabus, p11 |')
a('| Paper 1 Reading | 2 hours 15 minutes, 50 marks, 50%; AO1 30%, AO2 10%, AO3 60% | syllabus, pp10, 11, 19 |')
a('| Paper 2 Writing | 2 hours, 50 marks, 50%; AO2 80%, AO3 20% | syllabus, pp10, 11, 20 |')
a('| Grades | a–e on the AS route | syllabus, p10 |')
a('| Dictionaries | may not be used in either paper | syllabus, pp19, 20 |')
a('')
a('**The six tasks** (syllabus, pp19–21; the split of each question’s marks between AOs is corpus, from the level tables of every scheme):')
a('')
a('| task | text or brief | marks | AO1 | AO2 | AO3 | length |')
a('|---|---|---:|---:|---:|---:|---|')
a('| P1 Q1(a) directed response | one unseen text of about 550–750 words | 10 | 5 | 5 | — | 150–200 words |')
a('| P1 Q1(b) comparison (**Compare**) | the source and the candidate’s own 1(a) | 15 | 5 | — | 10 | — |')
a('| P1 Q2 text analysis (**Analyse**) | one unseen text of about 550–750 words | 25 | 5 | — | 20 | — |')
a('| P2 Q1(a) shorter writing | a prompt | 15 | — | 15 | — | no more than 400 words |')
a('| P2 Q1(b) reflective commentary | the candidate’s own 1(a) | 10 | — | — | 10 | — |')
a('| P2 Section B extended writing | one of three: imaginative/descriptive, discursive/argumentative, review/critical | 25 | — | 25 | — | 600–900 words |')
a('| **AS total** | | **100** | **15** | **45** | **40** | |')
a('')
a('The per-task split adds up to the syllabus weights exactly, which is why the practice bank below reproduces them exactly.')
a('')
a('**Command words** (syllabus, p23: the complete list is three) against the AS papers (corpus):')
a('')
a('| word | syllabus meaning | what the AS papers do with it | in prompts |')
a('|---|---|---|---|')
for c in FW['command_words']:
    use = ('opens %s in all %d papers, %s marks' % (c['observed']['where'], c['observed']['count'], c['modal_tariff'])
           if c['used_at_level'] else 'never used in the %d AS papers' % c['observed']['of_papers'])
    a('| **%s** | %s | %s | %s |' % (c['word'], c['meaning'], use, 'where a slot names it' if c['use_in_prompts'] else '**never** (C-14)'))
a('')
a('9093 at AS is **task-led**. Two listed words open the two Paper 1 analysis questions; every other task is an instruction to write, with a form, audience, purpose and length. So a prompt uses Compare or Analyse only where its slot names one, never Discuss, and otherwise the task form of the paper item it models.')
a('')
a('**The subject content** (syllabus, pp12–14) lists knowledge and skills, with examples that are **suggested, not prescribed** (p12). The linguistic elements it names — word classes, vocabulary, figurative language, phonology, morphology, rhetorical devices, voice, aspect, tense, modality, narrative perspective, word order and sentence structure, paragraph- and text-level structure, formality of tone, pragmatics — are the analytical vocabulary of topic 1.2. Teach them; never present them as a closed list.')
a('')
a('## 1. What the corpus says')
a('')
a('The full analysis is `%s`. What the plan takes from it:' % ANALYSIS)
a('')
a('- **What a grade takes** (corpus, median of %d series): Paper 1 c %s/50, a %s; Paper 2 c %s/50, a %s; AS c %s/100, a %s. The November series (the October 2026 sitting belongs to it) ran close to the median: an a needed %d–%d and a c %d–%d from 2021 to 2025. **A grade c is Level 3 on every table and an a is the bottom of Level 4** (our arithmetic). Level 5 is not needed for an a.' % (
    N_THR, int(med['P1_of_50']['C']), int(med['P1_of_50']['A']), int(med['P2_of_50']['C']), int(med['P2_of_50']['A']),
    int(med['AS_of_100']['c']), int(med['AS_of_100']['a']),
    min(v['a'] for v in thr['november_series'].values()), max(v['a'] for v in thr['november_series'].values()),
    min(v['c'] for v in thr['november_series'].values()), max(v['c'] for v in thr['november_series'].values())))
a('- **Analysis is forty of the hundred marks.** Across Paper 1 Questions 1(b) and 2 and Paper 2 Question 1(b), the same abilities are rewarded: choosing features of form, structure and language, quoting them briefly, and saying what each does for this audience. The toolkit (1.2) and evidence (1.3) topics exist for this.')
a('- **The ways of losing marks that recur across tasks** (report variants raising each, of 42):')
for r in sorted(SYSF, key=lambda r: -r['report_variants'])[:8]:
    a('  - %s — %d' % (r['failure'], r['report_variants']))
a('- **The misconception register** holds %d entries in `curriculum/misconceptions.json`, each with its evidence: the number of report variants whose sentences raise it, and the pattern that found them.' % len(MC['entries']))
a('- **Section B’s question order changes** from paper to paper (six orders in 34 papers), so a practice task names its category, never a question number.')
a('')
a('## 2. How the resource is organised')
a('')
a('*Judgement.* 9093 at AS has no list of topics to cover: its subject content (pp12–14) is the knowledge and skills the six tasks use, and the tasks are the subject. The knowledge they share (the conventions of forms, the analytical vocabulary, how evidence is written) sits in three foundation topics. The remaining topics are the paper sections. Section A of each paper is one topic, because its part (b) is written about the text its part (a) produced. Every objective is the syllabus’s own statement, transcribed with its page and verified against it.')
a('')
a('| topic | task | objectives | flashcards | tasks | practice texts | notes words |')
a('|---|---|---:|---:|---:|---:|---|')
for t in TOPICS:
    w, c = WO[t['id']], CT[t['id']]
    a('| **%s** %s | %s | %d | %d | %d | %d | %s–%s |' % (t['id'], t['title'], t['task'], len(t['objectives']), w['planned_flashcards'], w['planned_performance_tasks'], len(w['practice_texts']), fmt(c['depth_constraints']['word_budget']['min']), fmt(c['depth_constraints']['word_budget']['max'])))
a('| | | **%d** | **%d** | **%d** | **%d** | **%s–%s** |' % (N['obj'], N['flash'], N['perf'], N['texts'], fmt(N['nw'][0]), fmt(N['nw'][1])))
a('')
a('**The objectives** (syllabus text verbatim, page cited):')
a('')
a('| objective | syllabus text | page | AOs | command words |')
a('|---|---|---:|---|---|')
for o in REG['objectives']:
    if o.get('parent_id'):
        a('| %s | %s | %d | %s | %s |' % (o['objective_id'], o['syllabus_text'], o['syllabus_page'], ' '.join(o['assessment_objectives']), ', '.join(o['command_words']) or '—'))
a('')
a('Topics are authored in the order listed: the foundations first, because every later topic uses their terms.')
a('')
a('## 3. How each task is set and marked')
a('')
a('The full specification of every task, including each level table paraphrased band by band, is `curriculum/answer-shapes.json`. Marks, lengths, texts and AOs are **syllabus**; the AO split inside each question and the ladders are **corpus**, and every ladder appears with the same bands in all 34 schemes for its paper. Every task is marked by levels; there are no point-marked items at AS.')
a('')
for k, s in SH.items():
    line = '- **%s** (%s, %d marks)' % (s['name'], s['paper'], s['marks'])
    tops = []
    for tb in s['tables']:
        top = tb['levels'][0]
        tops.append('%s /%d, %d levels; top band %s: %s' % (tb['table'], tb['out_of'], len(tb['levels']), top['marks'], top['requires']))
    line += '. ' + ' • '.join(tops)
    if s.get('set_as'):
        line += '. Set as: %s' % s['set_as']
    a(line + '.')
a('')
a('Two marking rules matter for model answers (corpus, every scheme): the **word range is judged, not deducted** (an answer well outside it is a poorer fit to the task), and on Paper 1 **form, structure and language need not be taken in separate sections**.')
a('')
a('## 4. What each topic gets')
a('')
a('Every slot is decided in `topics/<T>/work_order.json` (and readable as `work_order.md`): its objective, subtype, AOs, **Bloom level**, and a one-line statement of what it teaches; for a performance task also its practice text, command word, tariff, the AO split of the table it models, and for a part (b) the part (a) it is written about.')
a('')
a('| subtype | cards | what it is for in 9093 |')
a('|---|---:|---|')
for m in FW['flashcard_subtype_ao_map']:
    if ST[m['subtype']]:
        a('| %s | %d | %s |' % (m['subtype'], ST[m['subtype']], m['tests']))
a('')
a('- **No flashcard models a paper item.** Every AS question is levels-marked and long, so cards carry no command word and no tariff. They teach the terms and moves the tasks are built from.')
a('- **MISCON cards** are discriminations, one per misconception-register entry, placed on the objective the error belongs to: the error, the correct move, and the test that tells them apart.')
a('- **APP, INTERP, MECH and EVAL cards supply their own sentence or short extract**, original and written for the card. A card never depends on a practice text or on another card.')
a('- **Performance tasks rehearse the paper twelve times over**: 12 directed responses and 12 comparisons on 12 Section A-style texts (1.4); 12 text analyses on 12 Section B-style texts (1.5); 12 shorter pieces and 12 reflective commentaries (2.1); 12 extended pieces, four per category (2.3, 2.4, 2.5). Around them sit short analysis tasks on extracts written into the prompt (1.1, 1.2, 1.3), style-matching (1.4), planning and paragraph building (2.2), and proofreading and rewriting (2.6).')
a('- **Paired tasks.** A part (b) is written about its part (a): the comparison compares the model directed response with the source; the commentary analyses the model shorter piece. The work order links them (`written_about`); the item carries the link in `prerequisite_item_ids`.')
a('- **AO balance by marks.** The rehearsed tasks carry %s marks of practice, AO1 %d%%, AO2 %d%%, AO3 %d%%: the syllabus weights exactly (largest gap %d points; `curriculum/ao_coverage.md`). Cards carry their objective’s AOs and no marks.' % (fmt(sum(aob['planned_marks'].values())), aob['planned_percent']['AO1'], aob['planned_percent']['AO2'], aob['planned_percent']['AO3'], aob['largest_gap_points']))
a('')
a('## 5. Bloom’s levels')
a('')
a('Every item carries its Bloom level and its AO; they are different axes. The level comes from the subtype for flashcards and from the task for performance items (`assessment-framework.json -> blooms_taxonomy`).')
a('')
a('| level | items | marks of practice carried by performance tasks |')
a('|---|---:|---:|')
for lv in ['Remember', 'Understand', 'Apply', 'Analyse', 'Evaluate', 'Create']:
    a('| %s | %d | %d |' % (lv, BL[lv], BLM[lv]))
a('')
a('By count the bank leans to Remember and Understand, because every analysis rests on exact terms and every writing task on known conventions. By marks it leans the other way: **Analyse carries %d and Create %d of the %s marks of rehearsed practice**, the shape of the examination.' % (BLM['Analyse'], BLM['Create'], fmt(sum(BLM.values()))))
a('')
a('## 6. Practice texts (RS-48)')
a('')
a('%d texts, each **original**, written for its tasks, held at `topics/<T>/texts/<text_id>.md` with front matter `text_id`, `title`, `genre`, `setting`, `written_for`, `words_min`, `words_max`, `original: true`. Check C-43 enforces the file, the declaration and the length. The length is the syllabus’s own: about 550–750 words (pp19–20).' % N['texts'])
a('')
a('| topic | texts | words each | what the texts must make possible |')
a('|---|---:|---|---|')
NEED = {'1.4': 'content a new form can re-use in 150–200 words (facts, a viewpoint, people, a place), and a clear form of its own with conventions to compare against the form the paired task sets',
        '1.5': 'a distinct form, audience and purpose; a structure worth analysing (a frame, shifts of focus, a turning point, an ending that answers the opening); language dense enough for twenty marks of analysis'}
for t in TOPICS:
    tx = WO[t['id']]['practice_texts']
    if tx:
        a('| %s | %d | %d–%d | %s |' % (t['id'], len(tx), tx[0]['words_min'], tx[0]['words_max'], NEED[t['id']]))
a('')
a('The work order gives each text its genre and subject, following the corpus shares: articles and features most often, then memoir, fiction, blogs, travel writing, speeches, reviews, brochures and appeals.')
a('')
a('*Judgement:* settings may be Namibian, southern African or international, as suits the genre; at least a third of each topic’s texts are set in Namibia or southern Africa. A text is never modelled on the subject of a Cambridge paper the author may know of.')
a('')
a('## 7. Answers and marking guidance')
a('')
a('- **Every paper-style task is levels-marked.** Write a model answer to the top band and inside the stated length. Then guidance that names, table by table, the band descriptors in `answer-shapes.json` the answer meets, in your own words, and one or two sentences on what a Level 3 answer to the same task would do instead, so a learner can place their own. A grade c is Level 3; say so where it helps.')
a('- **Directed responses and shorter writing**: the model answer is in the set form, for the set audience, with its conventions; the guidance names them.')
a('- **Comparisons and commentaries** quote their part (a) model answer and the source, in short embedded quotations.')
a('- **Short analysis tasks** (1.1, 1.2, 1.3): the model answer, then the features a complete answer identifies, each with its evidence and effect.')
a('- Every item’s guidance names the parts its subtype or task type declares (`subject-profile.yaml -> answer_structures`, checked by C-16).')
a('')
a('## 8. Scope')
a('')
a('- Not in this route, and scanned for by C-11: %s.' % ', '.join('`%s`' % x for x in NOT_IN_ROUTE))
a('- Never use the command word Discuss in a prompt (C-14): the AS papers never use it.')
a('- Never state a fixed deduction for word counts.')
a('- Each contract lists its adjacent topics: name them in passing if needed, teach them in their own topic.')
a('- %d conditioned mechanisms are registered (C-37): a short sentence creates emphasis *by contrast with the sentences around it*; a formal register is right *for an audience and a purpose*, not in general; a rhetorical question works *by the answer it invites*.' % len(CONDITIONED))
a('- Two category terms have variants that must be named wherever they appear (C-12): imaginative/descriptive (narrative, descriptive) and discursive/argumentative (discursive, argumentative).')
a('')
a('## 9. What the checks catch, and what they do not')
a('')
a('The suite checks structure, traceability, coverage of every objective, command-word discipline, declared answer parts, misconception cards, universals, scope terms, conditioned mechanisms and practice-text length. A worked slice of topic 1.5 in `%s/exemplar/` passes all of it (`python3 standard/v0.2.0-draft/mine/exemplar_9093.py --prove`), including a 25-mark model analysis of an original feature article.' % REL)
a('')
a('It cannot judge whether a model answer is really top band, whether a practice text reads well, or whether a text echoes a published one. Those need review, which under RS-42 runs on published material. After the run, `standard/v0.2.0-draft/mine/verify_9093.py` compares every item’s Bloom level, AOs, command word and tariff with its slot, and checks authored text against the corpus.')
a('')
a('## 10. Limits')
a('')
a('- No question-level assessment-evidence map is built for 9093, so C-39 reports not_run. Exposure is structural: every task is on every paper.')
a('- No third-party notes are approved for derivation; every claim is `generated_gap`.')
a('- The examiner reports held stop at March 2025. The misconception evidence counts spread across report variants; it does not measure how often an error costs marks.')
a('')
a('## Derivation policy')
a('')
a('Official assessment material is `mine_do_not_reproduce`. No question, text, task, title, mark-scheme or examiner-report wording appears in any learner-facing output. Mine the demand; write the text, the task and the answer yourself.')
a('')
open(os.path.join(WS, PLAN), 'w').write('\n'.join(P))

# =================================================================================== HANDOVER
H = []
h = H.append
h('# Handover prompt — Cambridge International AS Level English Language 9093')
h('')
h('Paste everything below the line into Hermes Agent or OpenCode with this repository open. It is self-contained: the agent needs no other instruction from you.')
h('')
h('---')
h('')
h('You are authoring the complete learner resource for **Cambridge International AS Level English Language, syllabus code 9093** (syllabus for 2024–2026, AS Level route). The learners are Namibian secondary students, English medium, sitting Paper 1 Reading and Paper 2 Writing in the October/November 2026 series, the first paper on %s. They may have nothing else to study from.' % FACTS['first_exam'])
h('')
h('## Start here')
h('')
h('Read these before writing anything:')
h('')
h('1. `AGENTS.md` (repo root) — which role brief applies. You are the AUTHOR.')
h('2. `%s/%s` — **the plan. This is your brief.** Read all of it.' % (REL, PLAN))
h('3. `%s/subject-profile.yaml` — the answer parts your marking guidance must name for each card subtype and task type, the conditioned mechanisms, the variant register, the prohibited patterns.' % REL)
h('4. `%s/curriculum/answer-shapes.json` — how every task is set and marked, with each level table paraphrased band by band.' % REL)
h('5. `standard/v0.2.0-draft/roles/AUTHOR.md` — written for business subjects. Where it conflicts with this handover, this handover wins for this subject: there are no Namibian-dollar figures or invented businesses here, and its "never say what a paper contains" means never claim frequencies or what examiners do. The syllabus’s own statements about a task (its marks, length, texts and AOs) are facts you may state.')
h('')
h('Everything is derived already. `%s/curriculum/syllabus-facts.json` records where each assessment value came from, with the syllabus page and the verbatim line, and every objective’s syllabus text was verified against its page. Do not re-derive them, do not re-read the syllabus PDF, and do not open any other subject’s workspace.' % REL)
h('')
h('## The job')
h('')
h('**%d topics, %s items (%s flashcards, %s performance tasks), %d original practice texts of %s–%s words, and %s–%s words of notes.** Work through the topics in this order and take the whole subject in one run. Do not stop after a topic to ask what is next.' % (len(TOPICS), fmt(N['items']), fmt(N['flash']), fmt(N['perf']), N['texts'], fmt(N['tw'][0]), fmt(N['tw'][1]), fmt(N['nw'][0]), fmt(N['nw'][1])))
h('')
h('```')
for t in TOPICS:
    h('  %-4s %s' % (t['id'], t['title']))
h('```')
h('')
h('9093 at AS is examined by **task**: six tasks on two papers, every one marked by levels. Topics 1.1–1.3 carry what every task uses (forms and audiences, the analytical vocabulary, how evidence is written); the rest are the paper sections. Forty of the hundred marks are for analysis (AO3), forty-five for writing (AO2), fifteen for reading the unseen text (AO1).')
h('')
h('For each topic `<T>`, read `%s/topics/<T>/contract.json` (scope, budgets, exclusions) and `%s/topics/<T>/work_order.json` (every slot, every practice text, pre-decided; `work_order.md` is the same thing as a table). Then produce, in `%s/topics/<T>/`:' % (REL, REL, REL))
h('')
h('1. `texts/<text_id>.md` — each practice text the work order lists, **written first**, because its tasks are answered from it. Front matter: `text_id`, `title`, `genre`, `setting`, `written_for`, `words_min`, `words_max`, `original: true`; then the text.')
h('2. `claims/canonical_claim_ledger.json` — every statement the topic teaches: definitions, the conventions of a form, the steps of a technique, why a choice has its effect. 3–6 per objective, each mapped to the objectives it serves.')
h('3. `content-units/CU-9093-<sub-topic>.json` — one unit per sub-topic in the work order, prose blocks that cite the claims they rest on.')
h('4. `learning-items/topic_<T>_items.json` — one item per slot, flashcards and performance tasks.')
h('5. Then render the notes and run the checks (commands at the end).')
h('')
h('**Structural exemplar.** `%s/exemplar/` is a small, complete slice of topic 1.5 that passes every check: a ledger, three content units, ten flashcards, a 25-mark text analysis answered from a practice text, and the text. Copy its **shape** — the field set of every claim, block and item, `context.text_id`, the text’s front matter, `claims_seen` and `authored_hash`, how the model analysis quotes briefly and is organised by effect. Do not copy its volume or its content. Do not reuse its text in topic 1.5.' % REL)
h('')
h('Every block and every item needs `claims_seen` (`{claim_id: revision}`), `authored_hash`, and `qa_status: "review_required"`. Compute the hash with:')
h('')
h('```python')
h('import sys, hashlib')
h("sys.path.insert(0, 'standard/v0.2.0-draft/checks')")
h('from yyeni_checks import _artefact_text')
h("x['authored_hash'] = hashlib.sha256(_artefact_text(x).encode()).hexdigest()")
h('```')
h('')
h('## Every item carries its labels')
h('')
h('Each slot has already decided `subtype` (or `item_type`), `assessment_objectives`, `blooms_level`, `command_word` and `mark_tariff`. **Carry all five onto the item**, plus `context.text_id` where the slot names a text. There are no sub-objectives in 9093: leave `sub_objectives` out.')
h('')
h('The item’s `item_id` is its slot id. After the run, the planner’s audit (`standard/v0.2.0-draft/mine/verify_9093.py`) compares every item with its slot; a difference not recorded in `authoring_notes.json` is reported as drift.')
h('')
h('- `assessment_objectives` (AO1 reading, AO2 writing, AO3 analysis) are what the examination credits.')
h('- `blooms_level` is what the learner is asked to do: Remember, Understand, Apply, Analyse, Evaluate, Create. A different axis, required on every item.')
h('- `command_word` and `mark_tariff` are null on every flashcard: no AS question is short enough for a card to model. Do not invent either.')
h('- **Paired tasks.** Where a performance slot has `written_about`, it is a part (b): author its part (a) first, put the part (a) item id in `prerequisite_item_ids`, and write the part (b) model answer about the part (a) model answer, quoting it. The part (b) prompt refers to "your" text from the previous task.')
h('')
h('If you change a slot’s subtype, change its Bloom level to match the plan’s section 5 and record the change.')
h('')
h('## Rules that come from the syllabus and the corpus')
h('')
h('Breaking one produces material that teaches something the papers do not ask, or asks it the wrong way.')
h('')
h('1. **The syllabus facts, and only those.** You may state what the syllabus states about a task: its marks, its length, its texts, its AOs, its categories (plan section 0). Never claim what examiners reward, report or want: the words "examiner" and "mark scheme" must not appear in learner-facing text (C-10). Teach the move and why it works. Never state a fixed deduction for a word count.')
h('2. **Command words.** Only three are listed, and only two are used at AS: `Compare` (Paper 1 Question 1(b)) and `Analyse` (Paper 1 Question 2). Use one where the slot names it. **Never use `Discuss`** (C-14). Elsewhere use the task form of the paper item the slot models: write a directed response in a stated form, role and audience; write no more than 400 words to a brief; write a reflective commentary; write 600–900 words in a named category. Vary your wording: never copy an instruction from a paper you may know.')
h('3. **Tariffs.** Use the slot’s. A task’s tariff and `ao_marks` decide which tables its guidance marks against.')
h('4. **Misconceptions.** Each MISCON slot names its entry in `curriculum/misconceptions.json`. A MISCON card is a **discrimination**: the error, the correct move, and the test that tells them apart — the `test` field gives it.')
h('5. **Glossary.** `curriculum/glossary.json` settles every term’s sense, including the pairs learners confuse (grammatical voice and a writer’s voice; tone and register; form and structure). Use them exactly.')
h('6. **Scope.** Never mention %s (C-11 scans for them). Adjacent topics in each contract: name in passing, teach there.' % ', '.join('`%s`' % x for x in NOT_IN_ROUTE))
h('7. **Truth.** No unqualified universals (always, never, only, every) unless definitional. Three registered mechanisms must carry their conditions wherever they appear (C-37): a short sentence creates emphasis by contrast with the sentences around it; a formal register is right for an audience and a purpose, not in general; a rhetorical question works by the answer it invites.')
h('8. **Variants.** Wherever imaginative/descriptive or discursive/argumentative appears, name its variants (narrative, descriptive; discursive, argumentative) and what each needs (C-12).')
h('9. **Self-containment.** A flashcard supplies its own sentence or extract — original, written for the card — and never depends on a practice text or another card. A performance task names its text by `context.text_id`, and its prompt refers to the text by its title and paragraph.')
h('10. **Nothing is reproduced.** No Cambridge text, question, task, title, mark-scheme or examiner-report wording, anywhere. Every text, prompt, model answer and piece of guidance is yours.')
h('11. **Filenames are derived, never chosen.** Do not pass `--out` to the renderer and do not rename anything afterwards.')
h('')
h('## Practice texts')
h('')
h('- **Original and the right length:** about 550–750 words, as the syllabus sets. The work order gives each text’s range, genre and subject. C-43 checks the file, the declaration and the length.')
h('- **Written for their tasks.** Plan section 6 says what each topic’s texts must make possible. A Section A text (1.4) must give its paired directed response content to re-use and a form of its own to compare against; a Section B text (1.5) must reward twenty marks of analysis. Write the text, then the items; revise the text if an item needs something it lacks.')
h('- **Real texts in form, not in fact.** A feature article reads like a feature article, with a headline, a standfirst and quoted voices; a memoir like a memoir. Invented people, places and organisations only; no real public figures quoted.')
h('- **Settings:** Namibian, southern African or international, as suits the genre, with at least a third of each topic’s texts set in Namibia or southern Africa.')
h('- Age-appropriate, and never modelled on the subject of a Cambridge paper you may know.')
h('')
h('## Answers and marking guidance')
h('')
h('- **Every paper-style task is levels-marked.** Write a model answer to the top band and inside the stated length. Then guidance that names, table by table, the band descriptors in `answer-shapes.json` the answer meets, in your own words, and one or two sentences on what a Level 3 answer to the same task would do instead.')
h('- **Analyses** (comparison, text analysis, commentary) quote briefly and embed their quotations, run feature, evidence, effect, link to purpose, and are organised by effect, not by paragraph order. The exemplar shows the shape.')
h('- **Writing tasks** keep to the form, audience, purpose and range; the guidance names the conventions used and the focus achieved.')
h('- The guidance must name every part `subject-profile.yaml -> answer_structures` declares for the subtype or task type (C-16).')
h('')
h('## Voice')
h('')
h('Plain, direct explanatory prose in British English, at AS level: precise terms, defined once and then used. Short paragraphs. Full teaching depth: the notes are the source the flashcards are cut from, the offline study text, and a standalone learning text at once. Every term and move is shown working on a short original extract. No hedging filler and no bullet-point soup where prose teaches better.')
h('')
h('## The work order is a baseline, not a cage')
h('')
h('Where a slot does not fit its objective, change it and record the change in `%s/topics/<T>/authoring_notes.json` as `{from, to, why}`. An unrecorded deviation is the only kind that is wrong. Where an exposure-required subtype genuinely does not fit, add an entry to the contract’s `subtype_waivers` with a reason of at least twelve words rather than padding the bank.' % REL)
h('')
h('## Finishing each topic')
h('')
h('```bash')
h('python3 standard/v0.2.0-draft/build/render_notes.py %s <T>' % REL)
h('python3 standard/v0.2.0-draft/checks/run_checks.py   %s <T>' % REL)
h('python3 standard/v0.2.0-draft/checks/what_to_fix.py  %s <T>' % REL)
h('```')
h('')
h('`what_to_fix.py` prints only failures, structure first, each with the action that clears it, and exits 0 when clean. Loop on it. Fix every **FAIL**. `not_run` on C-18 (no per-topic AO target, by design), C-35, C-39 and C-41 is expected. Set the contract’s `required_outputs.learning_items`, `required_outputs.content_units` and `required_outputs.practice_texts` to what you actually produced; a check compares them.')
h('')
h('When all %d topics are clean:' % len(TOPICS))
h('')
h('```bash')
h('python3 standard/v0.2.0-draft/build/publish_subject.py %s' % REL)
h('```')
h('')
h('It publishes only topics whose checks pass, carries each practice text with the tasks that use it, and reports any topic it skipped. The planner then audits the whole subject against its plan; you do not need to run that audit.')
h('')
h('## Boundaries')
h('')
h('- Do not edit anything under `standard/`, or anything in `%s/curriculum/`.' % REL)
h('- Do not touch any workspace other than `%s`, and do not edit `%s/exemplar/`.' % (REL, REL))
h('- Do not regenerate contracts or work orders; they are the plan you are working to.')
h('- There is no review round. The deterministic suite is the gate.')
h('')
h('## Report back when the subject is finished')
h('')
h('Under 250 words:')
h('')
h('- topics completed, and any not completed with the reason')
h('- totals: claims, content units, items, practice texts, notes words')
h('- the final check line per topic, or a single line if all read `PUBLISH`')
h('- every call you made rather than derived, and every deviation from a work order and why')
h('- anything in the plan that turned out to be wrong')
h('')
open(os.path.join(WS, HAND), 'w').write('\n'.join(H))
print('wrote %s (%d words) and %s (%d words)' % (PLAN, len('\n'.join(P).split()), HAND, len('\n'.join(H).split())))
